dekorateio/dekorate

pom.xml
Trying to address the remaining surefire failures.
=> fix: surefire failures.

core/src/main/java/io/ap4k/Session.java, core/src/main/java/io/ap4k/project/MavenInfo.java
- Fix #18. Error when maven project doesn't include a parent
- Correct typo error INASTANCE -> INSTANCE
=> Fix issue 18 - Error when maven project doesn't include a parent

annotations/component-annotations/src/main/java/io/ap4k/component/model/Component.java, annotations/component-annotations/src/main/java/io/ap4k/component/model/ComponentMappingProvider.java
- Change version `v1beta` to the correct `apiversion` which is `component.k8s.io/v1alpha1`
=> Change v1beta to the correct apiversion

annotations/component-annotations/src/main/java/io/ap4k/component/decorator/AddServiceInstanceToComponent.java
- Fix #54 
- Convert Parameter from ServiceCatalog to Component Model
=> Convert Parameter from ServiceCatalog to Component Model

annotations/component-annotations/src/main/java/io/ap4k/component/ComponentHandler.java, annotations/component-annotations/src/main/java/io/ap4k/component/adapt/CompositeConfigAdapter.java, annotations/component-annotations/src/main/java/io/ap4k/component/annotation/CompositeApplication.java, annotations/component-annotations/src/main/java/io/ap4k/component/annotation/Link.java, annotations/component-annotations/src/main/java/io/ap4k/component/decorator/AddLinkToComponent.java, annotations/component-annotations/src/main/java/io/ap4k/component/model/Link.java
- Fix #55
- Add Link annotation and fields
- Add decorator to inject Links
=> Add Link annotation

annotations/component-annotations/src/main/java/io/ap4k/component/processor/CompositeAnnotationProcessor.java, annotations/istio-annotations/src/main/java/io/ap4k/istio/processor/IstioAnnotationProcessor.java, annotations/kubernetes-annotations/src/main/java/io/ap4k/kubernetes/processor/KubernetesAnnotationProcessor.java, annotations/openshift-annotations/src/main/java/io/ap4k/openshift/processor/OpenshiftAnnotationProcessor.java, annotations/openshift-annotations/src/main/java/io/ap4k/openshift/processor/SourceToImageAnnotationProcessor.java, annotations/servicecatalog-annotations/src/main/java/io/ap4k/servicecatalog/processor/ServiceCatalogAnnotationProcessor.java, core/src/main/java/io/ap4k/Session.java
This is done to make things clearer (there is no mention of
generators in the design document)
=> refactor: Rename generators to handlers in Session

annotations/component-annotations/src/main/java/io/ap4k/component/processor/CompositeAnnotationProcessor.java, annotations/docker-annotations/src/main/java/io/ap4k/docker/processor/DockerBuildAnnotationProcessor.java, annotations/istio-annotations/src/main/java/io/ap4k/istio/processor/IstioAnnotationProcessor.java, annotations/kubernetes-annotations/src/main/java/io/ap4k/kubernetes/processor/KubernetesAnnotationProcessor.java, annotations/openshift-annotations/src/main/java/io/ap4k/openshift/processor/OpenshiftAnnotationProcessor.java, annotations/openshift-annotations/src/main/java/io/ap4k/openshift/processor/SourceToImageAnnotationProcessor.java, annotations/servicecatalog-annotations/src/main/java/io/ap4k/servicecatalog/processor/ServiceCatalogAnnotationProcessor.java, frameworks/micronaut/src/main/java/io/ap4k/micronaut/MicronautProcessor.java, frameworks/spring-boot/src/main/java/io/ap4k/spring/processor/SpringBootApplicationProcessor.java, frameworks/spring-boot/src/main/java/io/ap4k/spring/processor/SpringBootMappingProcessor.java, frameworks/thorntail/src/main/java/io/ap4k/thorntail/ThrorntailProcessor.java
There is an annoying warning when using the processors with java8+ that can potentially cause confusion. This pull request addresses this issue.
=> fix: set the correct supported source version on processors.

pom.xml
It will fail until items are synced in central.
=> chore: bump dependencies and application crd version.

annotations/kubernetes-annotations/pom.xml, annotations/kubernetes-annotations/src/main/java/io/ap4k/kubernetes/annotation/KubernetesApplication.java, annotations/kubernetes-annotations/src/main/java/io/ap4k/kubernetes/generator/DefaultKubernetesApplicationGenerator.java, annotations/kubernetes-annotations/src/main/resources/META-INF/services/io.ap4k.Generator, annotations/openshift-annotations/pom.xml, annotations/openshift-annotations/src/main/java/io/ap4k/openshift/annotation/OpenshiftApplication.java, annotations/openshift-annotations/src/main/java/io/ap4k/openshift/generator/DefaultOpenshiftApplicationGenerator.java, annotations/openshift-annotations/src/main/resources/META-INF/services/io.ap4k.Generator
=> feature: make k8s/openshift annotations usable from non-apt builds

annotations/kubernetes-annotations/src/test/java/io/ap4k/kubernetes/generator/KubernetesApplicationGeneratorTest.java, annotations/openshift-annotations/src/main/java/io/ap4k/openshift/generator/S2iBuildGenerator.java, annotations/openshift-annotations/src/main/java/io/ap4k/openshift/hook/OcBuildHook.java, annotations/openshift-annotations/src/test/java/io/ap4k/openshift/generator/OpenshiftApplicationGeneratorTest.java, core/src/main/java/io/ap4k/Session.java, core/src/main/java/io/ap4k/SessionWriter.java, core/src/main/java/io/ap4k/processor/AptWriter.java, core/src/main/java/io/ap4k/processor/SimpleFileWriter.java
Moreover the `SimpleFileWriter` now has the ability to forgo writing the
actual files on the filesystem thus giving the ability for integrations
to control this behavior
=> feat: session now returns a map to the generated resources

core/src/main/java/io/ap4k/project/GradleInfoReader.java
This import was preventing my IDE from running tests
=> fix: Remove unused import

core/src/main/java/io/ap4k/project/Project.java, core/src/main/java/io/ap4k/utils/Serialization.java, core/src/test/java/io/ap4k/project/ProjectParseAppResourceFileTest.java, core/src/test/resources/application.properties, core/src/test/resources/application.yaml, pom.xml
Requires: https://github.com/ap4k/dependencies/pull/1
=> feat: Support reading nested properties (just like yaml)

annotations/component-annotations/pom.xml, annotations/component-annotations/src/main/java/io/ap4k/component/configurator/ApplyProject.java, annotations/component-annotations/src/main/java/io/ap4k/component/decorator/AddRuntimeTypeToComponentDecorator.java, annotations/component-annotations/src/main/java/io/ap4k/component/decorator/AddRuntimeVersionToComponentDecorator.java, annotations/component-annotations/src/main/java/io/ap4k/component/generator/CompositeConfigGenerator.java, annotations/component-annotations/src/main/java/io/ap4k/component/handler/ComponentHandler.java, examples/spring-boot-with-svcat-and-component-on-kubernetes-example/src/test/java/io/ap4k/examples/ComponentServiceSpringBootExampleTest.java, frameworks/spring-boot/src/main/java/io/ap4k/spring/configurator/SetSpringBootVersion.java, frameworks/spring-boot/src/main/java/io/ap4k/spring/generator/SpringBootApplicationGenerator.java
- Ensure version presence in all scenarios.
- Modify integration tests to also check for version.
=> Make sure component version is always present.

frameworks/spring-boot/src/it/spring-cloud-kubernetes/src/test/java/io/ap4k/it/springbootwithspringcloudkubernetes/DemoApplicationTests.java, frameworks/spring-boot/src/main/java/io/ap4k/spring/generator/SpringBootApplicationGenerator.java
=> Change sck8s handler to check for Spring config

annotations/component-annotations/src/main/java/io/dekorate/component/model/BuildConfig.java
https://github.com/dekorateio/dekorate/issues/251.
@iocanel is there any test that I should update for this?
=> Add context path to build config

core/src/main/java/io/dekorate/kubernetes/decorator/AddAwsElasticBlockStoreVolumeDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddAzureDiskVolumeDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddAzureFileVolumeDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddConfigMapVolumeDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddPvcVolumeDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddSecretVolumeDecorator.java
AddXXXXXVolumeDecorator missing  `.endVolume()` code .
#262
=> fix: AddXXXXXVolumeDecorator missing some code

annotations/component-annotations/src/it/feat-229-override-annotationbased-config/src/main/resources/application.yml, annotations/component-annotations/src/it/feat-52-add-build-spec/src/main/java/io/dekorate/examples/component/Main.java, annotations/component-annotations/src/main/java/io/dekorate/component/handler/ComponentHandler.java, examples/component-example/src/test/java/io/dekorate/examples/ComponentSpringBootExampleTest.java
=> fix: BuildConfig should not be generated by default

core/src/main/java/io/dekorate/processor/AbstractAnnotationProcessor.java, core/src/main/java/io/dekorate/utils/Maps.java
=> refactor: deprecate mergeProperties in favour of Maps.merge

annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/annotation/HalkyonLink.java, annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/handler/LinkHandler.java, annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/model/LinkSpec.java, annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/model/Type.java
Sync API with halkyonio/api v1.0.0-beta.1.
=> Halkyon api update

annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/handler/ComponentHandler.java, core/pom.xml, core/src/main/java/io/dekorate/project/FileProjectFactory.java, core/src/main/java/io/dekorate/utils/Git.java, core/src/test/java/io/dekorate/utils/GitTest.java, core/src/test/java/io/dekorate/utils/SanitizeRemoteUrlTest.java, core/src/test/resources/git-gitlab/git/config, core/src/test/resources/git-ssh/git/HEAD, core/src/test/resources/git-ssh/git/config
Also make sure that the remote URL rewriting works for gitlab as well.
=> fix: make sure that we use a sanitized version of the git remote URL

readme.md
=> doc: add some doc about annotation-less usage

annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/handler/ComponentHandler.java, core/src/main/java/io/dekorate/project/Project.java, examples/halkyon-example/src/test/java/io/dekorate/examples/ComponentSpringBootExampleTest.java
=> fix: always generate buildconfig as long as we have proper git info

pom.xml
=> feat: autogenerate dekorate-bom and dekorate-spring-bom.

contributor-guidelines.md
----
Explain how to deal with the dependencies uberjar in Eclipse, Code, LSP and so on.
=> doc: Add a section about dealing with dependencies uberjar in Eclipse.

annotations/application-annotations/src/main/java/io/dekorate/application/generator/ApplicationResourceGenerator.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/generator/CustomResourceGenerator.java, annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/generator/CapabilityConfigGenerator.java, annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/generator/ComponentConfigGenerator.java, annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/generator/LinkConfigGenerator.java, annotations/jaeger-annotations/src/main/java/io/dekorate/jaeger/generator/JaegerAgentGenerator.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/apt/KubernetesAnnotationProcessor.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/generator/KubernetesApplicationGenerator.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/generator/OpenshiftApplicationGenerator.java, annotations/option-annotations/src/main/java/io/dekorate/option/generator/JvmOptionsGenerator.java, annotations/prometheus-annotations/src/main/java/io/dekorate/prometheus/generator/ServiceMonitorGenerator.java, annotations/servicecatalog-annotations/src/main/java/io/dekorate/servicecatalog/generator/ServiceCatalogGenerator.java, core/src/main/java/io/dekorate/AbstractKubernetesHandler.java, core/src/main/java/io/dekorate/Configurators.java, core/src/main/java/io/dekorate/config/AnnotationConfiguration.java, core/src/main/java/io/dekorate/config/ConfigurationSupplier.java, core/src/main/java/io/dekorate/config/PropertyConfiguration.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceDecorator.java, core/src/main/java/io/dekorate/utils/Beans.java, core/src/test/java/io/dekorate/utils/BeansTest.java, frameworks/spring-boot/src/it/issue-331-annotation-combined-with-properties/pom.xml, frameworks/spring-boot/src/it/issue-331-annotation-combined-with-properties/src/main/java/io/dekorate/annotationless/DemoApplication.java, frameworks/spring-boot/src/it/issue-331-annotation-combined-with-properties/src/main/resources/application.properties, frameworks/spring-boot/src/it/issue-331-annotation-combined-with-properties/src/test/java/io/dekorate/annotationless/Issue331Test.java, frameworks/spring-boot/src/main/java/io/dekorate/spring/apt/SpringBootApplicationProcessor.java, incubator/istio-annotations/src/main/java/io/dekorate/istio/generator/IstioConfigGenerator.java
----
The pull request also fixes some other issues found in the way:
- Handling of service account
- Prevent the same port from being added multiple times.
=> fix (#331) Properly combine annotations with properties.

core/src/main/java/io/dekorate/utils/Maps.java
style to nested.
----
So, I want to reuse this method in quarkus without having to copy paste all the dekorate internal stuff there.
=> feat: Maps now provides a method to convert a Map from properties

annotations/option-annotations/src/main/java/io/dekorate/option/configurator/ApplyJvmOptsConfigurator.java, design.md, examples/pom.xml, examples/readme.md, examples/spring-boot-on-openshift-example/src/main/java/io/dekorate/example/sbonopenshift/Main.java, examples/thorntail-on-kubernetes-example/Dockerfile, examples/thorntail-on-kubernetes-example/pom.xml, examples/thorntail-on-kubernetes-example/readme.md, examples/thorntail-on-kubernetes-example/src/main/java/io/dekorate/example/thorntailonkubernetes/HelloResource.java, examples/thorntail-on-kubernetes-example/src/main/java/io/dekorate/example/thorntailonkubernetes/RestApplication.java, examples/thorntail-on-kubernetes-example/src/main/resources/project-defaults.yml, examples/thorntail-on-kubernetes-example/src/test/java/io/dekorate/example/thorntailonkubernetes/ThorntailOnKubernetesIT.java, examples/thorntail-on-kubernetes-example/src/test/java/io/dekorate/example/thorntailonkubernetes/ThorntailOnKubernetesTest.java, examples/thorntail-on-openshift-example/pom.xml, examples/thorntail-on-openshift-example/readme.md, examples/thorntail-on-openshift-example/src/main/java/io/dekorate/example/thorntailonopenshift/HelloResource.java, examples/thorntail-on-openshift-example/src/main/java/io/dekorate/example/thorntailonopenshift/RestApplication.java, examples/thorntail-on-openshift-example/src/test/java/io/dekorate/example/thorntailonopenshift/ThorntailOnOpenshiftIT.java, examples/thorntail-on-openshift-example/src/test/java/io/dekorate/example/thorntailonopenshift/ThorntailOnOpenshiftTest.java, frameworks/thorntail/pom.xml, frameworks/thorntail/src/main/java/io/dekorate/thorntail/ThorntailConfigHolder.java, frameworks/thorntail/src/main/java/io/dekorate/thorntail/ThorntailProcessor.java, frameworks/thorntail/src/main/java/io/dekorate/thorntail/ThorntailWebAnnotationGenerator.java, frameworks/thorntail/src/main/java/io/dekorate/thorntail/configurator/ThorntailPrometheusAgentConfigurator.java, frameworks/thorntail/src/main/java/io/dekorate/thorntail/project/ThorntailGradleBuildInfoReader.java, frameworks/thorntail/src/main/java/io/dekorate/thorntail/project/ThorntailMavenBuildInfoReader.java, frameworks/thorntail/src/main/resources/META-INF/services/io.dekorate.project.BuildInfoReader, readme.md, starters/knative/knative-spring-starter/pom.xml, starters/openshift/openshift-thorntail-starter/pom.xml
Github farted and we can't reopen this one: https://github.com/dekorateio/dekorate/pull/336 so I created a new one.
=> Thorntail pt2.

frameworks/thorntail/src/it/annotationless-yml/pom.xml, frameworks/thorntail/src/it/annotationless-yml/src/main/java/io/dekorate/thorntail/it/RestApplication.java, frameworks/thorntail/src/it/annotationless-yml/src/main/resources/project-defaults.yml, frameworks/thorntail/src/it/annotationless-yml/src/test/java/io/dekorate/throntail/it/ThorntailAnnotationlessTest.java, frameworks/thorntail/src/main/java/io/dekorate/thorntail/ThorntailProcessor.java
This pull request allows thortail web projects to work in `annotationless` pretty much like spring boot does.
=> feat: Add annotationless support for throntail web projects.

config.md, core/src/main/java/io/dekorate/Session.java, core/src/main/java/io/dekorate/utils/Maps.java, core/src/main/java/io/dekorate/utils/Strings.java, core/src/test/java/io/dekorate/utils/MapsTest.java, core/src/test/java/io/dekorate/utils/StringsTest.java, core/src/test/resources/kebab.yml
=> feat: Add support for kebab casing when configuring dekorate via

doc/src/main/resources/annotation-doc.vm
=> fix: align the templates with code

core/src/main/java/io/dekorate/kubernetes/configurator/AddLivenessProbeConfigurator.java, core/src/main/java/io/dekorate/kubernetes/configurator/AddReadinessProbeConfigurator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AbstractAddProbeDecorator.java, core/src/main/java/io/dekorate/utils/Ports.java, frameworks/spring-boot/src/it/issue-369-probe-properties/Dockerfile, frameworks/spring-boot/src/it/issue-369-probe-properties/pom.xml, frameworks/spring-boot/src/it/issue-369-probe-properties/src/main/java/io/dekorate/annotationless/DemoApplication.java, frameworks/spring-boot/src/it/issue-369-probe-properties/src/main/resources/application.yml, frameworks/spring-boot/src/it/issue-369-probe-properties/src/test/java/io/dekorate/annotationless/Issue369Test.java, frameworks/spring-boot/src/main/java/io/dekorate/spring/generator/SpringBootApplicationGenerator.java
=> fix (#369): User probe configuration is now used even when spring

annotations/docker-annotations/src/main/java/io/dekorate/docker/annotation/DockerBuild.java, annotations/jib-annotations/src/main/java/io/dekorate/jib/annotation/JibBuild.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/handler/KubernetesHandler.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/annotation/S2iBuild.java, core/src/main/java/io/dekorate/kubernetes/config/ImageConfiguration.java, dependencies/pom.xml, tests/issue-409-image-customization/Dockerfile, tests/issue-409-image-customization/pom.xml, tests/issue-409-image-customization/src/main/java/io/dekorate/examples/kubernetes/Main.java, tests/issue-409-image-customization/src/main/resources/application.yml, tests/issue-409-image-customization/src/test/java/io/dekorate/examples/kuberentes/Issue409Test.java, tests/pom.xml
=> fix (#409): Allow users to configure image used via annotations and

core/src/main/java/io/dekorate/utils/Clients.java, core/src/main/java/io/dekorate/utils/Packaging.java, examples/pom.xml
This pull request adds/changes some utility that are really handy in downstream projects (e.g. quarkus) but doesn't make sense to host there.
=> Utility improvements for downstream projects

annotations/openshift-annotations/src/main/java/io/dekorate/openshift/OpenshiftAnnotations.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/OpenshiftLabels.java
=> 🦩 openshift typo 🦩

core/src/main/java/io/dekorate/kubernetes/decorator/AddEnvVarDecorator.java, tests/issue-473-env-from-field/pom.xml, tests/issue-473-env-from-field/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/issue-473-env-from-field/src/main/resources/application.properties, tests/issue-473-env-from-field/src/test/java/io/dekorate/annotationless/Issue473Test.java, tests/pom.xml
Fixes: #473 
Also adds a test and eliminates duplicate env vars.
=> fix: Handling of env from field.

core/src/main/java/io/dekorate/AbstractKubernetesHandler.java, core/src/main/java/io/dekorate/Resources.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddAnnotationDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddEnvVarDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddLabelDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddMountDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddPortDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddSidecarDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplicationContainerDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyArgsDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyCommandDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyImageDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyImagePullPolicyDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyServiceAccountNamedDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ContainerDecorator.java, examples/spring-boot-with-fmp-on-kubernetes-example/pom.xml
This pull request deals with decorator ordering.
Also, it makes it possible to override image pull policy by explicilty providing a decorator.
=> fix: Decorator override-ability

core/src/main/java/io/dekorate/processor/SimpleFileReader.java
Need an non-apt implementation of a SessionReader.
=> feat: Add a simple SessionReader impl for files

core/src/main/java/io/dekorate/Session.java, core/src/main/java/io/dekorate/logger/NoopLogger.java
Relates to: https://github.com/quarkusio/quarkus/issues/8798
=> Introduce the ability to use a custom logger

core/src/main/java/io/dekorate/SessionWriter.java, core/src/main/java/io/dekorate/processor/SimpleFileWriter.java
This  pull request allows us to whiteliest resource groups (e.g. knative, openshift etc).
This is going to be needed by the `decorate-cli`.
=> feat: Allow whitelisting resource groups.

core/src/main/java/io/dekorate/kubernetes/configurator/ApplyContainerPort.java, core/src/main/java/io/dekorate/utils/Beans.java, frameworks/spring-boot/src/main/java/io/dekorate/spring/generator/SpringBootWebAnnotationGenerator.java, tests/issue-545-spring-boot-web-with-port-path/pom.xml, tests/issue-545-spring-boot-web-with-port-path/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/issue-545-spring-boot-web-with-port-path/src/main/java/io/dekorate/annotationless/HelloController.java, tests/issue-545-spring-boot-web-with-port-path/src/main/resources/application.properties, tests/issue-545-spring-boot-web-with-port-path/src/test/java/io/dekorate/annotationless/Issue545Test.java, tests/pom.xml
Fixes: #545 
This pull request fixes some issues with the a bean merger, that is used to merge configuration together (property, annotation and framework configurration).
The main issue, is that when merging arrays, lists and set we didn't take ihertitence into account. This PR fixes that and also improves on the way we counfugre ports.
=> Fix (#545) Ports are now properly merged.

readme.md
This pull request adds some notes, on the dekorate brnaches and version we develop at the moment.
=> doc: Document the branch and version policy

core/src/main/java/io/dekorate/kubernetes/configurator/ApplyPort.java, core/src/main/java/io/dekorate/utils/Ports.java, frameworks/spring-boot/src/main/java/io/dekorate/spring/apt/SpringBootWebProcessor.java, frameworks/spring-boot/src/main/java/io/dekorate/spring/generator/SpringBootWebAnnotationGenerator.java, readme.md, tests/feat-547-spring-boot-request-mapping/pom.xml, tests/feat-547-spring-boot-request-mapping/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/feat-547-spring-boot-request-mapping/src/main/java/io/dekorate/annotationless/HelloController.java, tests/feat-547-spring-boot-request-mapping/src/main/resources/application.properties, tests/feat-547-spring-boot-request-mapping/src/test/java/io/dekorate/annotationless/Feat547Test.java, tests/pom.xml
Resolves: #547 
The idea is simple:
If the path configured for all @RestController share a common part, that part is automatically configured and exposed in the Ingress / Route.
=> feat (#547) Should handle path found in @RequestMapping.

readme.md, release.sh, site/getting-started/index.md, site/kubernetes/index.md, site/openshift/index.md
=> doc(#554) release script sets version to all pages of the site

core/src/main/java/io/dekorate/kubernetes/config/ImageConfiguration.java
=> fix(#564): group & part-of are now copied from app to image config

annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/HttpTransportVersion.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/KnativeApplication.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyPortNameDecorator.java, core/src/main/java/io/dekorate/utils/Maps.java, examples/knative-example/pom.xml, examples/knative-example/src/test/java/io/dekorate/examples/KnativeExampleTest.java
Earlier work added support for `http1` and `h2c` port names (see #491). 
However, the end result was not the expected.
=> Fix knative port issues

annotations/jib-annotations/src/main/java/io/dekorate/jib/buildservice/JibBuildService.java, annotations/jib-annotations/src/main/java/io/dekorate/jib/buildservice/JibBuildServiceFactory.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/ApplyDeploymentTriggerDecorator.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/listener/OpenshiftSessionListener.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/buildservice/S2iBuildServiceFactory.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/decorator/AddDockerImageStreamResourceDecorator.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/generator/S2iBuildGenerator.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/handler/S2iHanlder.java, examples/pom.xml, examples/spring-boot-on-openshift-with-docker-example/Dockerfile, examples/spring-boot-on-openshift-with-docker-example/pom.xml, examples/spring-boot-on-openshift-with-docker-example/readme.md, examples/spring-boot-on-openshift-with-docker-example/src/main/java/io/dekorate/example/sbonopenshift/Controller.java, examples/spring-boot-on-openshift-with-docker-example/src/main/java/io/dekorate/example/sbonopenshift/Main.java, examples/spring-boot-on-openshift-with-docker-example/src/main/resources/application.properties, examples/spring-boot-on-openshift-with-docker-example/src/test/java/io/dekorate/example/sbonopenshift/SpringBootOnOpenshiftIT.java, examples/spring-boot-on-openshift-with-docker-example/src/test/java/io/dekorate/example/sbonopenshift/SpringBootOnOpenshiftTest.java, examples/spring-boot-on-openshift-with-jib-example/pom.xml, examples/spring-boot-on-openshift-with-jib-example/readme.md, examples/spring-boot-on-openshift-with-jib-example/src/main/java/io/dekorate/example/sbonopenshift/Controller.java, examples/spring-boot-on-openshift-with-jib-example/src/main/java/io/dekorate/example/sbonopenshift/Main.java, examples/spring-boot-on-openshift-with-jib-example/src/main/resources/application.properties, examples/spring-boot-on-openshift-with-jib-example/src/test/java/io/dekorate/example/sbonopenshift/SpringBootOnOpenshiftIT.java, examples/spring-boot-on-openshift-with-jib-example/src/test/java/io/dekorate/example/sbonopenshift/SpringBootOnOpenshiftTest.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/OpenshiftExtension.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/annotation/OpenshiftIntegrationTest.java
=> Allow openshift with non s2i builds

annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/AutoScaling.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/GlobalAutoScaling.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/KnativeApplication.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/config/AutoScalerClass.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/config/AutoscalingMetric.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/config/HttpTransportVersion.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyGlobalAutoscalingClassDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyGlobalContainerConcurrencyDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyGlobalRequestsPerSecondTargetDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyGlobalTargetUtilizationDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalAutoscalingClassDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalAutoscalingMetricDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalAutoscalingTargetDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalContainerConcurrencyDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalTargetUtilizationPercentageDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddConfigMapResourceProvidingDecorator.java, readme.md, tests/feat-575-knative-global-autoscaling/pom.xml, tests/feat-575-knative-global-autoscaling/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/feat-575-knative-global-autoscaling/src/main/java/io/dekorate/annotationless/HelloController.java, tests/feat-575-knative-global-autoscaling/src/main/resources/application.properties, tests/feat-575-knative-global-autoscaling/src/test/java/io/dekorate/knative/Feat575GlobalAutoscalingTest.java, tests/feat-575-knative-local-autoscaling/pom.xml, tests/feat-575-knative-local-autoscaling/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/feat-575-knative-local-autoscaling/src/main/java/io/dekorate/annotationless/HelloController.java, tests/feat-575-knative-local-autoscaling/src/main/resources/application.properties, tests/feat-575-knative-local-autoscaling/src/test/java/io/dekorate/knative/Feat575LocalAutoscalingTest.java, tests/pom.xml
Resolves: #575 
Added all required configuration and decorators to support autoscaling.
=> feat (#575): Add autoscaling configuration support for knative.

annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/handler/S2iHanlder.java
=> fix (#571): JAVA_APP_JAR is now only set when s2i is used

annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/KnativeApplication.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java, readme.md, tests/feat-572-knative-cluster-local/pom.xml, tests/feat-572-knative-cluster-local/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/feat-572-knative-cluster-local/src/main/java/io/dekorate/annotationless/HelloController.java, tests/feat-572-knative-cluster-local/src/main/resources/application.properties, tests/feat-572-knative-cluster-local/src/test/java/io/dekorate/annotationless/Issue572Test.java, tests/pom.xml
=> feat (#572) Add support for cluster local services.

annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/KnativeApplication.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyMaxScaleDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyMinScaleDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddConfigMapDataDecorator.java
=> feat (#577) Add suport for knative scale bounds.

pom.xml, release.sh
=> Remove examples from release profile

annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddConfigMapDataDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/NamedResourceDecorator.java, tests/feat-575-knative-scale-to-zero/pom.xml, tests/feat-575-knative-scale-to-zero/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/feat-575-knative-scale-to-zero/src/main/java/io/dekorate/annotationless/HelloController.java, tests/feat-575-knative-scale-to-zero/src/main/resources/application.properties, tests/feat-575-knative-scale-to-zero/src/test/java/io/dekorate/knative/Feat575ScaleToZeroTest.java, tests/pom.xml
=> fix (#584): order of configmap decorators

annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/decorator/AddIngressDecorator.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/AddRouteDecorator.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/decorator/AddBuildConfigResourceDecorator.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/decorator/AddBuilderImageStreamResourceDecorator.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/decorator/AddDockerImageStreamResourceDecorator.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/decorator/AddOutputImageStreamResourceDecorator.java, annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/TaskProvidingDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddBasicAuthSecretDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddConfigMapResourceProvidingDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddRoleBindingResourceDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceAccountResourceDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ResourceProvidingDecorator.java
=> Resource Providing decorators now check for dublicates.

readme.md
=> doc (#593): Elaborate on branching and versions

site/getting-started/index.md
replacement for https://github.com/dekorateio/dekorateio.github.io/pull/2
=> fix property typos

assets/config.md, doc/pom.xml, doc/src/main/java/io/dekorate/doc/DocumentAnnotations.java
Resolves: #600 
This pull request:
- fixes broken tables in documentation
- updates tables with latest properties
- adds tekton config tables in the documentation
=> doc (#600): Update config.md

annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/decorator/AddIngressRuleDecorator.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/handler/KubernetesHandler.java
Resolves: #602 
The pull request improves handling of Ingress.
Allows adding additional hosts / path configuration when no matching config is found, or updating existing ones.
=> Finer Ingress control

annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/KubernetesApplication.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/RollingUpdate.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/config/DeploymentStrategy.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/decorator/ApplyDeploymentStrategyDecorator.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/handler/KubernetesHandler.java, tests/feat-590-custom-rolling-update-strategy/pom.xml, tests/feat-590-custom-rolling-update-strategy/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/feat-590-custom-rolling-update-strategy/src/main/java/io/dekorate/annotationless/HelloController.java, tests/feat-590-custom-rolling-update-strategy/src/main/resources/application.properties, tests/feat-590-custom-rolling-update-strategy/src/test/java/io/dekorate/annotationless/Feat590Test.java, tests/pom.xml
=> feat (#590): Add support for deployment strategy.

core/src/main/java/io/dekorate/utils/Gradle.java, core/src/main/java/io/dekorate/utils/Maven.java
=> fix (#610): Maven / Gradle version utils no longer throw exceptions

core/src/main/java/io/dekorate/project/GradleInfoReader.java
Close #616 
not work for mixed language project, such as Kotlin +Java
=> fix: add kotlin annotation processor support

core/src/main/java/io/dekorate/utils/Packaging.java
Packaging used to only allow adding files/entries directly in the tarball root.
It should be possible to use a destination path inside the tarball (or entry prefix path if it makes more sense).
Related to: https://github.com/quarkusio/quarkus/pull/11760/files
=> feat (#621) Packaging now allows to set a custom tar destination.

core/src/main/java/io/dekorate/kubernetes/decorator/ApplyPortNameDecorator.java
=> chore: remove uneeded System.out.println()

readme.md
=> doc (#622): Improve doc on exposing ingress/routes

annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/KubernetesApplication.java, core/src/main/java/io/dekorate/AbstractKubernetesHandler.java, core/src/main/java/io/dekorate/kubernetes/annotation/Base.java, core/src/main/java/io/dekorate/kubernetes/annotation/HostAlias.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddHostAliasesDecorator.java, examples/kubernetes-example-with-hostaliases/Dockerfile, examples/kubernetes-example-with-hostaliases/pom.xml, examples/kubernetes-example-with-hostaliases/readme.md, examples/kubernetes-example-with-hostaliases/src/main/java/io/dekorate/examples/kubernetes/Controller.java, examples/kubernetes-example-with-hostaliases/src/main/java/io/dekorate/examples/kubernetes/Main.java, examples/kubernetes-example-with-hostaliases/src/test/java/io/dekorate/examples/KubernetesExampleTest.java
Allow the generation of hostAliases property from Deployment
Signed-off-by: Vincent Sourtin <sourin-v@bridgestone-bae.com>
=> Kubernetes HostAliases property

core/src/main/java/io/dekorate/processor/SimpleFileWriter.java, core/src/main/java/io/dekorate/project/GradleInfoReader.java
=> Fix issues with gradle and kotlin (#632)

annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/KubernetesApplication.java, core/src/main/java/io/dekorate/AbstractKubernetesHandler.java, core/src/main/java/io/dekorate/kubernetes/annotation/Base.java, core/src/main/java/io/dekorate/kubernetes/annotation/HostAlias.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddHostAliasesDecorator.java, examples/kubernetes-example-with-hostaliases/Dockerfile, examples/kubernetes-example-with-hostaliases/pom.xml, examples/kubernetes-example-with-hostaliases/readme.md, examples/kubernetes-example-with-hostaliases/src/main/java/io/dekorate/examples/kubernetes/Controller.java, examples/kubernetes-example-with-hostaliases/src/main/java/io/dekorate/examples/kubernetes/Main.java, examples/kubernetes-example-with-hostaliases/src/test/java/io/dekorate/examples/KubernetesExampleTest.java
Allow the generation of hostAliases property from Deployment
Signed-off-by: Vincent Sourtin <sourin-v@bridgestone-bae.com>
=> Kubernetes HostAliases property (for branch 0.12.x)

core/src/main/java/io/dekorate/project/BuildInfo.java, core/src/test/java/io/dekorate/project/GradleInfoReaderTest.java, core/src/test/java/io/dekorate/project/ProjectParseResourceFileTest.java
=> Fix Issue #640 Gradle resource dir not set properly

annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/handler/KubernetesHandler.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java, examples/kubernetes-example-with-custom-image-name/Dockerfile, examples/kubernetes-example-with-custom-image-name/pom.xml, examples/kubernetes-example-with-custom-image-name/readme.md, examples/kubernetes-example-with-custom-image-name/src/main/java/io/dekorate/examples/kubernetes/Main.java, examples/kubernetes-example-with-custom-image-name/src/test/java/io/dekorate/examples/KubernetesExampleTest.java, examples/pom.xml, readme.md
=> fix (#620): image property is not properly read. Add doc.

annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/KnativeApplication.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/Traffic.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyRevisionNameDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyTrafficDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java, tests/feat-642-knative-traffic-splitting/pom.xml, tests/feat-642-knative-traffic-splitting/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/feat-642-knative-traffic-splitting/src/main/java/io/dekorate/annotationless/HelloController.java, tests/feat-642-knative-traffic-splitting/src/main/resources/application.properties, tests/feat-642-knative-traffic-splitting/src/test/java/io/dekorate/knative/Feat642TrafficSplittingTest.java, tests/pom.xml
=> feat(#642): Add support for traffic rules on knative services.

core/src/main/java/io/dekorate/kubernetes/decorator/AddPortDecorator.java, core/src/test/java/io/dekorate/kubernetes/decorator/AddPortDecoratorTest.java
Fix for one of the issues reported in https://github.com/quarkusio/quarkus/issues/12826
=> fix: NPE when apply port decorator to nameless ports.

annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/handler/KubernetesHandler.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/ApplyDeploymentTriggerDecorator.java, core/src/main/java/io/dekorate/kubernetes/adapter/ContainerAdapter.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddAnnotationDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddEnvVarDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddLabelDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddMountDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddPortDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplicationContainerDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyApplicationContainerDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyArgsDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyCommandDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyImageDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyImagePullPolicyDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyLimitsCpuDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyLimitsMemoryDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyPortNameDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyRequestsCpuDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/ApplyRequestsMemoryDecorator.java, core/src/main/java/io/dekorate/utils/Predicates.java, examples/spring-boot-with-existing-manifests-on-kubernetes-example/src/main/resources/existing-manifests/kubernetes.yml, examples/spring-boot-with-existing-manifests-on-kubernetes-example/src/test/java/io/dekorate/examples/sbexistingmanifests/ExistingManifestsExampleTest.java
Adds test and performs minor improvements related to: https://github.com/quarkusio/quarkus/issues/12826
In detail:
- It supports matching unamed containers.
- Adds tests for the above case
- Minor code cleanup
=> Improve handling support of `bring your own container`.

annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/AddAwsElasticBlockStoreVolumeToRevisionDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/AddAzureDiskVolumeToRevisionDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/AddAzureFileVolumeToRevisionDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/AddConfigMapVolumeToRevisionDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/AddHostAliasesToRevisionDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/AddInitContainerToRevisionDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/AddPvcVolumeToRevisionDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/AddSecretVolumeToRevisionDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/AddSidecarToRevisionDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java, core/src/main/java/io/dekorate/AbstractKubernetesHandler.java, readme.md, tests/issue-687-knative-volumes/pom.xml, tests/issue-687-knative-volumes/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/issue-687-knative-volumes/src/main/java/io/dekorate/annotationless/HelloController.java, tests/issue-687-knative-volumes/src/main/resources/application.properties, tests/issue-687-knative-volumes/src/test/java/io/dekorate/knative/Issue687KnativeVolumeTest.java, tests/pom.xml
=> Fix handling of pod spec decorators in knative

annotations/crd-annotations/src/main/java/io/dekorate/crd/annotation/PrinterColumn.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/decorator/AddAdditionPrinterColumnDecorator.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/decorator/AddStatusReplicasPathDecorator.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/handler/CustomResourceHandler.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/util/JsonSchema.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/util/Types.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/visitor/AdditionalPrineterColumnDetector.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/visitor/AnnotatedMultiPropertyPathDetector.java, examples/pojo-to-crd-karaf-example/src/main/java/io/dekorate/examples/pojo2crd/KarafSpec.java, readme.md
This pull request, introduces support for additional printer columns.
=> Introduce support for additonal printer columns in crd-annotations

annotations/crd-annotations/src/main/java/io/dekorate/crd/handler/CustomResourceHandler.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/util/JsonSchema.java, examples/pojo-to-crd-zookeeper-example/pom.xml, examples/pojo-to-crd-zookeeper-example/readme.md, examples/pojo-to-crd-zookeeper-example/src/main/java/io/dekorate/examples/pojo2crd/v1/Zookeeper.java, examples/pojo-to-crd-zookeeper-example/src/main/java/io/dekorate/examples/pojo2crd/v1/ZookeeperSpec.java, examples/pojo-to-crd-zookeeper-example/src/main/java/io/dekorate/examples/pojo2crd/v1/ZookeeperStatus.java, examples/pojo-to-crd-zookeeper-example/src/test/java/io/dekorate/examples/pojo2crd/CustomResourceTest.java, readme.md
=> feat: ignore (kind, apiVersion & metadata) in the generated crd

annotations/crd-annotations/src/main/java/io/dekorate/crd/decorator/PromoteSingleVersionAttributesDecorator.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/handler/CustomResourceHandler.java, core/src/main/java/io/dekorate/Configurators.java, examples/pojo-to-crd-karaf-example/src/test/java/io/dekorate/examples/pojo2crd/CustomResourceTest.java
=> Promote single version attributes to top-level

readme.md
Adding extra note to the readme to consider using 2.0.0-alpha.
I did not wanted to use exact version as this might quickly oudate
=> chore: Add note for usage

annotations/crd-annotations/src/main/java/io/dekorate/crd/util/JsonSchema.java, annotations/crd-annotations/src/test/java/io/dekorate/crd/example/recipe/Recipe.java, annotations/crd-annotations/src/test/java/io/dekorate/crd/util/JsonSchemaTest.java, examples/pom.xml
The pull request adds custom handling for the custom kubernetes types:
- Duration
- Quantity
- IntOrString
=> fix: schema generator now maps custom k8s types to string.

annotations/crd-annotations/src/main/java/io/dekorate/crd/handler/CustomResourceHandler.java, annotations/crd-annotations/src/main/java/io/dekorate/crd/util/JsonSchema.java, annotations/crd-annotations/src/test/java/io/dekorate/crd/util/JsonSchemaTest.java
Better support intorstring based types using anyOf.
=> fix: handling of intorstring types.

testing/core-junit/src/main/java/io/dekorate/testing/Testing.java, testing/core-junit/src/main/java/io/dekorate/testing/WithClosables.java, testing/core-junit/src/main/java/io/dekorate/testing/WithDiagnostics.java, testing/core-junit/src/main/java/io/dekorate/testing/WithKubernetesClient.java, testing/core-junit/src/main/java/io/dekorate/testing/WithPod.java, testing/kubernetes-junit/src/main/java/io/dekorate/testing/kubernetes/KubernetesExtension.java, testing/kubernetes-junit/src/main/java/io/dekorate/testing/kubernetes/WithKubernetesResources.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/DeploymentConfigDiagnostics.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/OpenshiftExtension.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/WithOpenshiftResources.java
Add handling for internal errrors.
Fix NPEs
Minor changes
=> feat: improve diagnostics handling for internal errors

annotations/knative-annotations/pom.xml, annotations/knative-annotations/src/main/java/io/dekorate/knative/manifest/KnativeManifestGenerator.java, annotations/kubernetes-annotations/pom.xml, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/manifest/KubernetesManifestGenerator.java, annotations/openshift-annotations/pom.xml, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/manifest/OpenshiftManifestGenerator.java, annotations/option-annotations/src/main/java/io/dekorate/option/annotation/VcsOptions.java, annotations/option-annotations/src/main/java/io/dekorate/option/apt/VcsOptionsProcessor.java, annotations/option-annotations/src/main/java/io/dekorate/option/config/DefaultVcsConfigGenerator.java, annotations/option-annotations/src/main/java/io/dekorate/option/config/DefaultVcsConfigGeneratorFactory.java, annotations/option-annotations/src/main/java/io/dekorate/option/config/VcsConfigGenerator.java, annotations/option-annotations/src/main/resources/META-INF/services/io.dekorate.ConfigurationGeneratorFactory, annotations/option-annotations/src/main/resources/META-INF/services/javax.annotation.processing.Processor, annotations/tekton-annotations/src/main/java/io/dekorate/tekton/manifest/TektonManifestGenerator.java, core/src/main/java/io/dekorate/AbstractKubernetesConfigurationHandler.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddVcsUrlAnnotationDecorator.java, core/src/main/java/io/dekorate/project/FileProjectFactory.java, core/src/main/java/io/dekorate/project/ScmInfo.java, core/src/main/java/io/dekorate/utils/Git.java, core/src/test/java/io/dekorate/utils/GitTest.java, core/src/test/resources/git-simple/git/config, readme.md, testing/core-junit/src/main/java/io/dekorate/testing/DeploymentDiagnostics.java, testing/core-junit/src/main/java/io/dekorate/testing/PodDiagnostics.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/DeploymentConfigDiagnostics.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/ImageStreamDiagnostics.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/ImageStreamDiagnosticsFactory.java, testing/openshift-junit/src/main/resources/META-INF/services/io.dekorate.testing.DiagnosticsFactory
The idea is to provide the following features:
- ability to select remote that will fuel vcs annotations on resources
- introduce feature flag for vcs url sanitization
=> Introduce vcs options

core/src/main/java/io/dekorate/kubernetes/configurator/SetPortPath.java, core/src/main/java/io/dekorate/utils/Ports.java, frameworks/jaxrs/pom.xml, frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/adapter/JaxrsConfigAdapter.java, frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/apt/ApplicationPathAnnotationProcessor.java, frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/apt/PathAnnotationProcessor.java, frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/config/DefaultJaxrsConfigGenerator.java, frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/config/DefaultJaxrsConfigGeneratorFactory.java, frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/config/JaxrsConfig.java, frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/config/JaxrsConfigGenerator.java, frameworks/jaxrs/src/main/resources/META-INF/services/io.dekorate.ConfigurationGeneratorFactory, frameworks/jaxrs/src/main/resources/META-INF/services/javax.annotation.processing.Processor, frameworks/pom.xml
=> feat: Allow jaxrs to be used independantly of thorntail

core/src/main/java/io/dekorate/project/GradleInfoReader.java, core/src/test/java/io/dekorate/project/GradleInfoReaderTest.java, core/src/test/resources/gradle/gradle-versioned-doublequotes/build.gradle
=> fix: support doublequoted version definition

annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/decorator/AddIngressDecorator.java, core/src/main/java/io/dekorate/kubernetes/configurator/ApplyPort.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java
Relates to: https://github.com/quarkusio/quarkus/issues/16817
=> fix: Guard against host port being null

annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/decorator/AddIngressRuleDecorator.java, examples/frameworkless-on-kubernetes-example/pom.xml, examples/frameworkless-on-openshift-example/pom.xml, examples/knative-example/pom.xml, examples/kubernetes-with-configmap-volume-example/pom.xml, examples/kubernetes-with-custom-image-name-example/pom.xml, examples/kubernetes-with-hostaliases-example/pom.xml, examples/pom.xml, examples/servicebinding-annotationless-example/pom.xml, examples/servicebinding-example/pom.xml, examples/spring-boot-on-kubernetes-example/pom.xml, examples/spring-boot-on-kubernetes-with-jib-example/pom.xml, examples/spring-boot-on-kubernetes-without-annotations/pom.xml, examples/spring-boot-on-openshift-example/pom.xml, examples/spring-boot-on-openshift-with-docker-example/pom.xml, examples/spring-boot-on-openshift-with-jib-example/pom.xml, examples/spring-boot-with-existing-manifests-on-kubernetes-example/pom.xml, examples/spring-boot-with-fmp-on-kubernetes-example/pom.xml, examples/spring-boot-with-gradle-on-openshift-example/pom.xml, examples/spring-boot-with-groovy-on-openshift-example/pom.xml, examples/spring-boot-with-jaeger-on-kubernetes-example/pom.xml, examples/spring-boot-with-prometheus-on-kubernetes-example/pom.xml, examples/spring-boot-with-tekton-and-m2-pvc-example/pom.xml, examples/spring-boot-with-tekton-example/pom.xml, examples/thorntail-on-kubernetes-example/pom.xml, examples/thorntail-on-openshift-example/pom.xml, examples/vertx-on-kubernetes-example/pom.xml, examples/vertx-on-openshift-example/pom.xml
The pull request properly adds path and pathType on Ingress rules
=> Fix broken Ingress v1 rule

core/src/main/java/io/dekorate/utils/Serialization.java, core/src/main/java/io/dekorate/utils/serialization/Features.java, core/src/main/java/io/dekorate/utils/serialization/SerializationFeatures.java, tests/issue-769-old-jackson-version/pom.xml, tests/issue-769-old-jackson-version/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/issue-769-old-jackson-version/src/main/java/io/dekorate/annotationless/HelloController.java, tests/issue-769-old-jackson-version/src/main/resources/application.properties, tests/issue-769-old-jackson-version/src/test/java/io/dekorate/example/Issue769Test.java, tests/pom.xml
=> fix: check if Jackson feature exist before setting them

examples/multimodule-projects-on-kubernetes-example/multimodule-project-tests-on-kubernetes-example/src/test/java/io/dekorate/example/SpringBootForMultiModuleAppsOnKubernetesIT.java, examples/multimodule-projects-on-openshift-example/multimodule-project-tests-on-openshift-example/src/test/java/io/dekorate/example/SpringBootForMultiModuleAppsOnOpenshiftIT.java, examples/spring-boot-on-kubernetes-example/pom.xml, examples/spring-boot-on-kubernetes-example/src/main/java/io/dekorate/example/Main.java, examples/spring-boot-on-kubernetes-example/src/test/java/io/dekorate/example/SpringBootOnKubernetesIT.java, testing/core-junit/src/main/java/io/dekorate/testing/WithDiagnostics.java, testing/core-junit/src/main/java/io/dekorate/testing/WithProject.java, testing/kubernetes-junit/src/main/java/io/dekorate/testing/kubernetes/KubernetesExtension.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/OpenshiftExtension.java
And fix them if they are failing.
=> Reenable tests for MultiModule projects

examples/multimodule-projects-on-kubernetes-example/multimodule-project-tests-on-kubernetes-example/src/test/java/io/dekorate/example/SpringBootForMultiModuleAppsOnKubernetesIT.java, examples/multimodule-projects-on-openshift-example/multimodule-project-tests-on-openshift-example/src/test/java/io/dekorate/example/SpringBootForMultiModuleAppsOnOpenshiftIT.java, examples/spring-boot-on-kubernetes-example/src/test/java/io/dekorate/example/SpringBootOnKubernetesIT.java, testing/core-junit/src/main/java/io/dekorate/testing/WithDiagnostics.java, testing/core-junit/src/main/java/io/dekorate/testing/WithProject.java, testing/kubernetes-junit/src/main/java/io/dekorate/testing/kubernetes/KubernetesExtension.java, testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/OpenshiftExtension.java
Update the disabled message for failures with the following issue: https://github.com/dekorateio/dekorate/issues/818
=> Fix Diagnosis for failures ++ Update Disabled Tests with linking issue

core/src/main/java/io/dekorate/utils/Ports.java
=> Add comment explaining port names

.github/workflows/integration-tests.yml, examples/frameworkless-on-kubernetes-example/src/test/java/io/dekorate/example/RestApiFrameworklessOnK8sIT.java, examples/frameworkless-on-kubernetes-example/src/test/java/io/dekorate/example/RestApiFrameworklessOnK8sTest.java
This PR should fix #865. 
You can observe a successful run of the GH Actions here: https://github.com/ammbra/dekorate/actions/runs/1887904057
=> Fix tests in frameworkless example

.github/workflows/integration-tests-with-dockerio.yml, .github/workflows/integration-tests.yml, annotations/knative-annotations/src/main/java/io/dekorate/knative/apt/KnativeAnnotationProcessor.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/listener/KnativeSessionListener.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/manifest/KnativeManifestGenerator.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/listener/OpenshiftSessionListener.java, docs/documentation/junit-extensions.md, examples/knative-example/Dockerfile, examples/knative-example/pom.xml, examples/knative-example/readme.md, examples/knative-example/src/test/java/io/dekorate/example/KnativeExampleIT.java, examples/pom.xml, examples/spring-boot-on-kubernetes-example/readme.md, testing/knative-junit/pom.xml, testing/knative-junit/src/main/java/io/dekorate/testing/annotation/KnativeIntegrationTest.java, testing/knative-junit/src/main/java/io/dekorate/testing/knative/KnativeExtension.java, testing/knative-junit/src/main/java/io/dekorate/testing/knative/WithKnativeClient.java, testing/knative-junit/src/main/java/io/dekorate/testing/knative/WithKnativeConfig.java, testing/knative-junit/src/main/java/io/dekorate/testing/knative/WithKnativeIntegrationTestConfig.java, testing/knative-junit/src/main/java/io/dekorate/testing/knative/WithKnativeResources.java, testing/knative-junit/src/main/java/io/dekorate/testing/knative/WithKnativeRoute.java, testing/knative-junit/src/main/java/io/dekorate/testing/knative/WithKnativeService.java, testing/pom.xml
Updated documentation with the new JUnit extension for Knative.
Fix https://github.com/dekorateio/dekorate/issues/570
=> Add deploy and testing support for knative

annotations/docker-annotations/src/main/java/io/dekorate/docker/apt/DockerAnnotationProcessor.java, annotations/helm-annotations/src/main/java/io/dekorate/helm/apt/HelmAnnotationProcessor.java, annotations/jaeger-annotations/src/main/java/io/dekorate/jaeger/apt/JaegerAgentAnnotationProcessor.java, annotations/jib-annotations/src/main/java/io/dekorate/jib/apt/JibProcessor.java, annotations/kind-annotations/src/main/java/io/dekorate/kind/apt/KindAnnotationProcessor.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/apt/KnativeAnnotationProcessor.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/apt/KubernetesAnnotationProcessor.java, annotations/minikube-annotations/src/main/java/io/dekorate/minikube/apt/MinikubeAnnotationProcessor.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/apt/OpenshiftAnnotationProcessor.java, annotations/option-annotations/src/main/java/io/dekorate/option/apt/GeneratorOptionsProcessor.java, annotations/option-annotations/src/main/java/io/dekorate/option/apt/JvmOptionsProcessor.java, annotations/option-annotations/src/main/java/io/dekorate/option/apt/VcsOptionsProcessor.java, annotations/prometheus-annotations/src/main/java/io/dekorate/prometheus/apt/ServiceMonitorAnnotationProcessor.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/apt/S2iAnnotationProcessor.java, annotations/servicebinding-annotations/src/main/java/io/dekorate/servicebinding/apt/ServiceBindingAnnotationProcessor.java, annotations/tekton-annotations/src/main/java/io/dekorate/tekton/apt/TektonAnnotationProcessor.java, core/src/main/java/io/dekorate/apt/DekorateProcessor.java, frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/apt/ApplicationPathAnnotationProcessor.java, frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/apt/PathAnnotationProcessor.java, frameworks/spring-boot/src/main/java/io/dekorate/spring/apt/SpringBootApplicationProcessor.java, frameworks/spring-boot/src/main/java/io/dekorate/spring/apt/SpringBootBeanProcessor.java, frameworks/spring-boot/src/main/java/io/dekorate/spring/apt/SpringBootWebProcessor.java, frameworks/thorntail/src/main/java/io/dekorate/thorntail/ThorntailProcessor.java
=> fix: add supported source version annotations

examples/helm-on-kubernetes-example/pom.xml, examples/helm-on-openshift-example/pom.xml, examples/knative-example/pom.xml, examples/kubernetes-with-configmap-volume-example/pom.xml, examples/kubernetes-with-custom-image-name-example/pom.xml, examples/kubernetes-with-hostaliases-example/pom.xml, examples/multimodule-projects-on-kubernetes-example/multimodule-project-a-on-kubernetes-example/pom.xml, examples/multimodule-projects-on-kubernetes-example/multimodule-project-b-on-kubernetes-example/pom.xml, examples/multimodule-projects-on-openshift-example/multimodule-project-a-on-openshift-example/pom.xml, examples/multimodule-projects-on-openshift-example/multimodule-project-b-on-openshift-example/pom.xml, examples/spring-boot-on-kubernetes-example/pom.xml, examples/spring-boot-on-kubernetes-with-jib-custom-registry-example/pom.xml, examples/spring-boot-on-kubernetes-with-jib-example/pom.xml, examples/spring-boot-on-kubernetes-with-sbo-example/pom.xml, examples/spring-boot-on-kubernetes-without-annotations/pom.xml, examples/spring-boot-on-openshift-example/pom.xml, examples/spring-boot-on-openshift-with-dekorate-profile-example/pom.xml, examples/spring-boot-on-openshift-with-docker-example/pom.xml, examples/spring-boot-on-openshift-with-jib-custom-registry-example/pom.xml, examples/spring-boot-on-openshift-with-ocp-properties-example/pom.xml, examples/spring-boot-with-existing-manifests-on-kubernetes-example/pom.xml, examples/spring-boot-with-fmp-on-kubernetes-example/pom.xml, examples/spring-boot-with-groovy-on-openshift-example/pom.xml, examples/spring-boot-with-jaeger-on-kubernetes-example/pom.xml, examples/spring-boot-with-prometheus-on-kubernetes-example/pom.xml, examples/spring-boot-with-tekton-and-m2-pvc-example/pom.xml, examples/spring-boot-with-tekton-example/pom.xml, pom.xml, tests/issue-791-missing-imagestream-with-default-configuration/pom.xml
=> chore: updates spring boot version

annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalTargetUtilizationPercentageDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyMaxScaleDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyMinScaleDecorator.java, annotations/knative-annotations/src/main/java/io/dekorate/knative/manifest/KnativeManifestGenerator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceAccountResourceDecorator.java, examples/knative-example/src/test/java/io/dekorate/example/KnativeExampleTest.java, tests/issue-586-knative-scale-bounds/src/test/java/io/dekorate/knative/Issue586ScaleBoundsTest.java, tests/issue-939-knative-container-concurrency/pom.xml, tests/issue-939-knative-container-concurrency/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/issue-939-knative-container-concurrency/src/main/java/io/dekorate/annotationless/HelloController.java, tests/issue-939-knative-container-concurrency/src/main/resources/application.properties, tests/issue-939-knative-container-concurrency/src/main/resources/kubernetes/knative.yml, tests/issue-939-knative-container-concurrency/src/test/java/io/dekorate/knative/Issue939KnativeContainerConcurrencyTest.java, tests/pom.xml
Resolves: #939 
Additionally, changes knative annotations to kebab style which is the kubernetes standard.
=> Knative fixes

.gitignore, docs/README.md, docs/_layouts/base.html
This is using a useful tool anchorjs: https://www.bryanbraun.com/anchorjs/
I tested these changes by building and running the site locally using Docker (I've added the instructions too).
Fix https://github.com/dekorateio/dekorate/issues/944
=> feat: automatically add hyperlinks to all titles

assets/config.md, core/src/main/java/io/dekorate/kubernetes/annotation/ConfigMapVolume.java, core/src/main/java/io/dekorate/kubernetes/annotation/Item.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddConfigMapVolumeDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddSecretVolumeDecorator.java, docs/configuration-guide.md, tests/feat-943-configmap-volumes/pom.xml, tests/feat-943-configmap-volumes/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/feat-943-configmap-volumes/src/main/resources/application.properties, tests/feat-943-configmap-volumes/src/test/java/io/dekorate/annotationless/Feat943Test.java, tests/issue-446-secret-volumes/src/main/resources/application.properties, tests/pom.xml
Fix https://github.com/dekorateio/dekorate/issues/943
=> feat: map items in ConfigMap and Secret volumes

core/src/main/java/io/dekorate/utils/Maps.java
This pull request addresses the issue with the `AnnotationTypeMismatchException`. that occurs in some cases using JDK 11+ when trying to read the Ingress from the KubernetesApplication.
The workaround catch the `Exception` (`AnnotationTypeMismatchException` seems uncatchable, maybe it's proxied or something like this) and returns the default value for the method. As the issue seems to only take place when no explicit value is specified falling back to the default return value seems good enough.
=> fix: work around AnnotationTypeMismatchException.

annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, annotations/helm-annotations/src/main/java/io/dekorate/helm/util/HelmExpressionParser.java, annotations/helm-annotations/src/test/java/io/dekorate/helm/util/HelmExpressionParserTest.java, annotations/helm-annotations/src/test/resources/expected-no-changes-kubernetes.yml, annotations/helm-annotations/src/test/resources/expected-parseArrayExpression-kubernetes.yml, annotations/helm-annotations/src/test/resources/expected-parseExpressionWithCommandArray-kubernetes.yml, annotations/helm-annotations/src/test/resources/expected-parseExpressionWithEscape-kubernetes.yml, annotations/helm-annotations/src/test/resources/expected-parseExpressionWithOrOperatorAndFound-kubernetes.yml, annotations/helm-annotations/src/test/resources/expected-parseExpressionWithSeveralFilters-kubernetes.yml, annotations/helm-annotations/src/test/resources/expected-parseSimpleExpression-kubernetes.yml, annotations/helm-annotations/src/test/resources/test-kubernetes.yml, core/src/main/java/io/dekorate/kubernetes/decorator/AbstractAddProbeDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddLivenessProbeDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddReadinessProbeDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddStartupProbeDecorator.java, core/src/main/java/io/dekorate/utils/Serialization.java, docs/documentation/helm.md, examples/helm-on-kubernetes-example/pom.xml, examples/helm-on-kubernetes-example/src/main/resources/application.properties, examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
Fix https://github.com/dekorateio/dekorate/issues/973
=> feat: helm to support health check properties auto mapping

annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/AddLabelToDeploymentSelectorDecorator.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/RemoveLabelFromDeploymentSelectorDecorator.java, annotations/s2i-annotations/src/main/java/io/dekorate/s2i/manifest/S2iManifestGenerator.java, core/src/main/java/io/dekorate/AbstractKubernetesManifestGenerator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddToMatchingLabelsDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/DeploymentSelectorDecoratorFactory.java, core/src/main/java/io/dekorate/kubernetes/decorator/RemoveFromMatchingLabelsDecorator.java, core/src/main/resources/META-INF/services/io.dekorate.SelectorDecoratorFactory, tests/feat-886-openshift-deployment-kind-with-deployment/src/test/java/io/dekorate/annotationless/Issue886Test.java
Add the matching label selectors (which is only for Deployment kind) within the SelectorDecoratorFactory.
This will also fix https://github.com/quarkusio/quarkus/issues/26522
=> Configure label selectors for Deployment

core/src/main/java/io/dekorate/AbstractKubernetesManifestGenerator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java, docs/documentation/helm.md, examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
Change requested by Ana Maria.
=> Add service type as preconfigured properties in Helm extension

core/src/main/java/io/dekorate/project/MavenInfoReader.java, tests/feat-941-existing-common-resources/pom.xml, tests/feat-941-existing-common-resources/src/main/resources/kubernetes/common.yml
Fix https://github.com/dekorateio/dekorate/issues/1017
=> Change Maven resources dir from "src/main/resources" to "target/classes"

examples/spring-boot-on-knative-example/src/main/java/io/dekorate/example/Main.java, examples/spring-boot-on-kubernetes-example/src/main/java/io/dekorate/example/Main.java
I thing that keeping these examples as simple as possible only with dekorte dependency is a good idea, WDYT?
=> simplifying SB examples

annotations/helm-annotations/src/main/java/io/dekorate/helm/annotation/ValueReference.java, annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, assets/config.md, core/src/main/java/io/dekorate/ConfigReference.java, docs/configuration-guide.md, docs/documentation/helm.md, examples/helm-on-kubernetes-example/src/main/resources/application.properties, examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java, examples/helm-on-kubernetes-example/src/test/resources/expected-ingress.yaml
Fix https://github.com/dekorateio/dekorate/issues/1038
=> Support complex Helm expressions

annotations/helm-annotations/src/main/java/io/dekorate/helm/annotation/HelmChart.java, annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
Related to https://github.com/quarkiverse/quarkus-helm/issues/61
=> feat: allow configuring the api version in Helm

annotations/helm-annotations/src/main/java/io/dekorate/helm/annotation/HelmDependency.java, annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, annotations/helm-annotations/src/main/java/io/dekorate/helm/model/HelmDependency.java, assets/config.md, docs/configuration-guide.md, examples/helm-on-kubernetes-example/src/main/resources/application.properties, examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
These two properties are new in Helm chart API version v2: https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags
This is necessary for https://github.com/quarkiverse/quarkus-helm/issues/67
=> Helm: Add new properties `conditions` and `tags`

docs/documentation/cert-manager.md, docs/documentation/container-resources.md, docs/documentation/explicit-annotation-processors.md, docs/documentation/get-started.md, docs/documentation/gs-generic-java.md, docs/documentation/gs-spring-boot.md, docs/documentation/helm.md, docs/documentation/junit-extensions.md, docs/documentation/knative.md, docs/documentation/kubernetes.md, docs/documentation/minikube.md, docs/documentation/openshift.md, docs/documentation/spring-boot-integration.md, docs/documentation/tekton.md, docs/documentation/using-bom.md
Fix https://github.com/dekorateio/dekorate/issues/1055
=> release: update the guides using the project.yml data

core/src/main/java/io/dekorate/kubernetes/decorator/CronJobSelectorDecoratorFactory.java, core/src/main/java/io/dekorate/kubernetes/decorator/JobSelectorDecoratorFactory.java, core/src/main/resources/META-INF/services/io.dekorate.SelectorDecoratorFactory, tests/feat-886-kubernetes-deployment-kind-with-cronjob/src/test/java/io/dekorate/annotationless/Issue886Test.java, tests/feat-886-kubernetes-deployment-kind-with-job/src/test/java/io/dekorate/annotationless/Issue886Test.java
This is related to this comment: https://github.com/quarkusio/quarkus/pull/27425#issuecomment-1243635947
=> Generate match labels for CronJob/Job resources

annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java
This is necessary to overcome the Dekorate limitation where we cannot use Object fields in annotations.
This way we can allow other extensions like Quarkus Helm supports this.
=> fix: provide the config references in helm before running the helm stage

core/src/main/java/io/dekorate/kubernetes/annotation/Protocol.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java, tests/issue-775-duplicate-service-port/src/main/resources/application.properties, tests/issue-775-duplicate-service-port/src/test/java/io/dekorate/example/Issue775TwoPortsTest.java
fix https://github.com/dekorateio/dekorate/issues/1068
=> fix: add protocol in service resources

annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, examples/helm-on-kubernetes-example/src/main/resources/kubernetes/helm/values.schema.json, examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
Related to https://github.com/quarkiverse/quarkus-helm/issues/71
=> Add values.schema.json in the generated Helm chart

annotations/kind-annotations/src/main/java/io/dekorate/kind/decorator/ApplyPortToKindServiceDecorator.java
Fix https://github.com/dekorateio/dekorate/issues/1077
=> Prevent null pointer in ApplyPortToKindServiceDecorator

core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java
Related to https://github.com/dekorateio/dekorate/commit/5ae740904618f0402cfaecd30b747b64f65b0503
=> Add protocol for default ports in services

.github/workflows/downstream-projects-check.yml
Fix https://github.com/snowdrop/team/issues/928
Note that I've only added three snowdrop examples:
- rest http: the basic one
- crud: to verify when having Helm dependencies
- cache: to verify multiple apps
=> Cover Snowdrop Examples in Dekorate CI for K8s and Helm

annotations/tekton-annotations/pom.xml
Related to https://github.com/iocanel/dekorate/commit/4190eae27fa14d74194d88629343af38e4023638
=> Add manifest to teknon shaded jars

annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/AddHostToRouteDecorator.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/AddPortToRouteDecorator.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/AddRouteDecorator.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/AddServiceToRouteDecorator.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/manifest/OpenshiftManifestGenerator.java, docs/documentation/helm.md, tests/issue-existing-route-resource/pom.xml, tests/issue-existing-route-resource/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/issue-existing-route-resource/src/main/java/io/dekorate/annotationless/HelloController.java, tests/issue-existing-route-resource/src/main/resources/application.properties, tests/issue-existing-route-resource/src/main/resources/kubernetes/common.yml, tests/issue-existing-route-resource/src/test/java/io/dekorate/example/IssueExistingRouteResourceTest.java, tests/pom.xml
Relates https://github.com/quarkusio/quarkus/issues/29899
=> Split the route decorator to allow custom resources

annotations/knative-annotations/src/main/java/io/dekorate/knative/manifest/KnativeManifestGenerator.java, tests/issue-knative-existing-deployment-resource/pom.xml, tests/issue-knative-existing-deployment-resource/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/issue-knative-existing-deployment-resource/src/main/java/io/dekorate/annotationless/HelloController.java, tests/issue-knative-existing-deployment-resource/src/main/resources/application.properties, tests/issue-knative-existing-deployment-resource/src/main/resources/kubernetes/knative.yml, tests/issue-knative-existing-deployment-resource/src/test/java/io/dekorate/example/IssueExistingDeploymentResourceTest.java, tests/pom.xml
Relates https://github.com/quarkusio/quarkus/issues/29962
=> Knative: not rename the container port for all deployments

annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java
Related to https://github.com/quarkiverse/quarkus-helm/issues/153
=> Helm: Use latest decorator that was used instead of the first

annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/Ingress.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/decorator/AddIngressDecorator.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/decorator/AddIngressRuleDecorator.java, annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/manifest/KubernetesManifestGenerator.java, assets/config.md, docs/configuration-guide.md, tests/issue-1123-ingress-multiple-container-ports/pom.xml, tests/issue-1123-ingress-multiple-container-ports/src/main/java/io/dekorate/ingress/DemoApplication.java, tests/issue-1123-ingress-multiple-container-ports/src/main/resources/application.properties, tests/issue-1123-ingress-multiple-container-ports/src/test/java/io/dekorate/ingress/Issue1123Test.java, tests/pom.xml
Fix https://github.com/dekorateio/dekorate/issues/1123
=> Add `target-port` property in Ingress to select the port to use

annotations/openshift-annotations/src/main/java/io/dekorate/openshift/annotation/Route.java, annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/AddPortToRouteDecorator.java, tests/issue-1124-route-multiple-container-ports/pom.xml, tests/issue-1124-route-multiple-container-ports/src/main/java/io/dekorate/route/DemoApplication.java, tests/issue-1124-route-multiple-container-ports/src/main/resources/application.properties, tests/issue-1124-route-multiple-container-ports/src/test/java/io/dekorate/route/Issue1124Test.java, tests/pom.xml
And avoid using the problematic `getHttpPort(config)`. 
Fix https://github.com/dekorateio/dekorate/issues/1124
=> Set default `http` to `openshift.route.target-port` property

annotations/helm-annotations/pom.xml
Release notes: https://github.com/yaml-path/YamlPath/releases/tag/0.0.5
=> Bump yaml-path to 0.0.5

core/src/main/java/io/dekorate/processor/SimpleFileReader.java
Relates to: [#30558](https://github.com/quarkusio/quarkus/issues/30558)
=> Downgrade logging message in SimpleFileReader

.github/workflows/integration-tests-with-dockerio.yml, .github/workflows/integration-tests.yml
Cherrypicks from the main branch.
=> [2.11.x] Fix workflows

annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, examples/helm-on-kubernetes-example/src/main/resources/kubernetes/helm/Chart.yaml, examples/helm-on-kubernetes-example/src/main/resources/kubernetes/helm/values.yaml, examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
Relates https://github.com/quarkiverse/quarkus-helm/pull/166
=> Helm: Provided application config from custom values.yaml should take priority

annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, examples/helm-on-kubernetes-example/src/main/resources/application.properties
Relates https://github.com/quarkiverse/quarkus-helm/pull/171
=> Fix profile property is ignored for values without a path

annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, examples/helm-on-kubernetes-example/src/main/resources/kubernetes/helm/crds/crontabs.stable.example.com.yaml, examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
Relates https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/ 
Relates https://github.com/quarkiverse/quarkus-helm/issues/174
=> Helm: Add crd folder if does exist from helm input directory

core/src/main/java/io/dekorate/utils/Development.java
Relates to https://github.com/quarkusio/quarkus/issues/31355
Before these changes, the Topological Sort algorithm took around 50 ms to finish, and now it takes < 1 ms.
=> Refactor performance of isVerbose

annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, annotations/helm-annotations/src/main/java/io/dekorate/helm/util/MapUtils.java
Relates https://github.com/quarkiverse/quarkus-helm/issues/201
=> Helm: Sort generated values files

annotations/helm-annotations/src/main/java/io/dekorate/helm/util/HelmConfigUtils.java, assets/config.md, docs/configuration-guide.md, examples/helm-on-kubernetes-example/src/main/resources/application.properties, examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
Relates https://github.com/quarkiverse/quarkus-helm/issues/209
=> Helm: Support rootless properties via configuration

annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java, annotations/helm-annotations/src/main/java/io/dekorate/helm/util/YamlExpressionParserUtils.java, core/src/main/java/io/dekorate/ConfigReference.java, tests/issue-knative-probes-helm/pom.xml, tests/issue-knative-probes-helm/src/main/java/io/dekorate/knative/helm/DemoApplication.java, tests/issue-knative-probes-helm/src/main/java/io/dekorate/knative/helm/HelloController.java, tests/issue-knative-probes-helm/src/main/resources/application.properties, tests/issue-knative-probes-helm/src/test/java/io/dekorate/knative/helm/KnativeWithHelmTest.java, tests/pom.xml
This issue happens when having multiple extensions at the classpath. 
Relates https://github.com/quarkiverse/quarkus-helm/pull/222
=> Helm: Fix handling of Knative probes

pom.xml
https://github.com/fabric8io/kubernetes-client/releases/tag/v6.6.0
=> bump kubernetes-client.version from 6.5.1 to 6.6.0

pom.xml
https://github.com/fabric8io/kubernetes-client/releases/tag/v6.6.2
=> Bump Fabric8 Kubernetes Client to 6.6.2

core/src/main/java/io/dekorate/kubernetes/decorator/AddInitContainerDecorator.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddSidecarDecorator.java, tests/feat-overwrite-sidecar-containers/pom.xml, tests/feat-overwrite-sidecar-containers/src/main/java/io/dekorate/annotationless/DemoApplication.java, tests/feat-overwrite-sidecar-containers/src/main/java/io/dekorate/annotationless/HelloController.java, tests/feat-overwrite-sidecar-containers/src/main/resources/application.properties, tests/feat-overwrite-sidecar-containers/src/test/java/io/dekorate/example/FeatOverwriteSidecarContainersTest.java, tests/pom.xml
Related to https://github.com/dekorateio/dekorate/pull/1196#pullrequestreview-1436202301
=> Support overwrite values from existing sidecar containers

formatter/pom.xml
=> fix: add release configuration to formatter pom

annotations/helm-annotations/pom.xml
Changes: https://github.com/yaml-path/YamlPath/releases/tag/0.0.9
=> Bump YAMLPath to 0.0.9

core/src/main/java/io/dekorate/kubernetes/adapter/ContainerAdapter.java, core/src/main/java/io/dekorate/kubernetes/decorator/AddSidecarDecorator.java, tests/feat-overwrite-sidecar-containers/src/main/resources/application.properties, tests/feat-overwrite-sidecar-containers/src/test/java/io/dekorate/example/FeatOverwriteSidecarContainersTest.java
Relates to https://github.com/quarkusio/quarkus/issues/35006
=> Fix container adapter to set the workingDir property

core/src/main/java/io/dekorate/project/GradleInfoReader.java
=> fix: remove double quotes from values  in settings.gralde

pom.xml
Required for https://github.com/quarkusio/quarkus/pull/36312
Relates to https://github.com/fabric8io/kubernetes-client/issues/5479
=> deps: bump sundrio to 0.101.3

annotations/openshift-annotations/src/test/java/io/dekorate/openshift/generator/OpenshiftConfigGeneratorTest.java, core/src/main/java/io/dekorate/kubernetes/decorator/DeploymentResourceFactory.java, core/src/main/java/io/dekorate/project/GradleInfoReader.java, tests/issue-1271-containers-empty-in-deployment/pom.xml, tests/issue-1271-containers-empty-in-deployment/readme.md, tests/issue-1271-containers-empty-in-deployment/src/main/java/io/dekorate/example/Controller.java, tests/issue-1271-containers-empty-in-deployment/src/main/java/io/dekorate/example/Main.java, tests/issue-1271-containers-empty-in-deployment/src/main/resources/application.properties, tests/issue-1271-containers-empty-in-deployment/src/test/java/io/dekorate/example/SpringBootOnOpenshiftIT.java, tests/issue-1271-containers-empty-in-deployment/src/test/java/io/dekorate/example/SpringBootOnOpenshiftTest.java, tests/pom.xml
=> Add PodSpecTemplate for Deployment kind in Openshift

docs/documentation/jib-build-hook.md, readme.md
Hi there,
there was a mistake in the docs regarding jib-annotations.
Please accept my pull-request 🍀
=> fixed jib-annotations dependency docs

annotations/helm-annotations/pom.xml
=> feat: provide helm model classifier

docs/documentation/annotation-less-configuration.md
=> Remove wrong line in annotation-less-configuration.md file

core/src/main/java/io/dekorate/kubernetes/decorator/AddLabelDecorator.java
When I tried something like `new AddLabelDecorator(name, label.getKey(), label.getValue(), ROUTE)` it didn't work. I figured out this fix which fixed it for my case but feel free to point any issues since this is my first PR to this project.
=> Fix Label not using correct kinds

pom.xml
Bump Kubernetes Client to latest version.
=> chore(deps): Bump version.kubernetes-client from 6.9.2 to 6.13.0

.github/workflows/build.yml, .github/workflows/integration-tests-with-dockerio.yml, .github/workflows/integration-tests.yml, docs/Gemfile, docs/Gemfile.lock
See: https://github.com/dekorateio/dekorate/security/dependabot/80
=> fix: dependabot alert about http request smuggling in ruby webrick
