dekorateio/dekorate

- annotations/component-annotations/src/main/java/io/ap4k/component/ComponentHandler.java
- annotations/component-annotations/src/main/java/io/ap4k/component/annotation/CompositeApplication.java
- examples/component-example/src/main/java/io/ap4k/examples/component/Main.java
- Fix issue #39 
- Add envVars to CompositeAnnotation
- Issues discovered: **EnvVar is added twice - see issue 28** AND **runtime doesn't appear anymore**
```
spec:
deploymentMode: "innerloop"
exposeService: false
image: []
env:
- name: "key1"
value: "val1"
- name: "key1"
value: "val1"
```
> Add envVars to CompositeAnnotation

- annotations/component-annotations/src/main/java/io/ap4k/component/ComponentHandler.java
- examples/component-example/src/main/java/io/ap4k/examples/component/Main.java
- Add missing method `withExposeService` to the componentHandler. 
- Enrich the `Component example` with `name` and `exposService` fields
> Add missing method withExposeService

- annotations/docker-annotations/src/main/java/io/ap4k/docker/registrar/EnableDockerBuildRegistrar.java
- annotations/openshift-annotations/src/main/java/io/ap4k/openshift/generator/S2iBuildGenerator.java
- core/src/main/java/io/ap4k/Session.java
- core/src/main/java/io/ap4k/SessionListener.java
My recent refactoring completely broke all hooks. This is a fix for it.
> fix: Register hooks when session is closing().

- annotations/kubernetes-annotations/src/main/java/io/ap4k/kubernetes/generator/KubernetesApplicationGenerator.java
- annotations/kubernetes-annotations/src/main/java/io/ap4k/kubernetes/handler/KubernetesHandler.java
- annotations/openshift-annotations/src/main/java/io/ap4k/openshift/handler/OpenshiftHandler.java
- annotations/pom.xml
- annotations/prometheus-annotations/pom.xml
- annotations/prometheus-annotations/src/main/java/io/ap4k/prometheus/annotation/EnableServiceMonitor.java
- annotations/prometheus-annotations/src/main/java/io/ap4k/prometheus/apt/ServiceMonitorAnnotationProcessor.java
- annotations/prometheus-annotations/src/main/java/io/ap4k/prometheus/decorator/EndpointPathDecorator.java
- annotations/prometheus-annotations/src/main/java/io/ap4k/prometheus/generator/ServiceMonitorGenerator.java
- annotations/prometheus-annotations/src/main/java/io/ap4k/prometheus/handler/ServiceMonitorHandler.java
- annotations/prometheus-annotations/src/main/java/io/ap4k/prometheus/model/Endpoint.java
- annotations/prometheus-annotations/src/main/java/io/ap4k/prometheus/model/ServiceMonitor.java
- annotations/prometheus-annotations/src/main/java/io/ap4k/prometheus/model/ServiceMonitorSpec.java
- annotations/prometheus-annotations/src/main/resources/META-INF/services/javax.annotation.processing.Processor
- core/src/main/java/io/ap4k/AbstractKubernetesHandler.java
- core/src/main/java/io/ap4k/Resources.java
- core/src/main/java/io/ap4k/Session.java
- core/src/main/java/io/ap4k/SessionWriter.java
- core/src/main/java/io/ap4k/kubernetes/decorator/AddServiceDecorator.java
- core/src/main/java/io/ap4k/processor/AptWriter.java
- examples/pom.xml
- examples/spring-boot-with-prometheus-on-kubernetes-example/Dockerfile
- examples/spring-boot-with-prometheus-on-kubernetes-example/pom.xml
- examples/spring-boot-with-prometheus-on-kubernetes-example/src/main/java/io/ap4k/example/sbonkubernetes/Main.java
- examples/spring-boot-with-prometheus-on-kubernetes-example/src/main/resources/application.properties
- frameworks/spring-boot/pom.xml
- frameworks/spring-boot/src/main/java/io/ap4k/spring/config/SpringApplicationConfig.java
- frameworks/spring-boot/src/main/java/io/ap4k/spring/generator/SpringBootApplicationGenerator.java
- readme.md
The goal of this pull request is to add intiial support for prometheus annotations. 
It introduced `EnableServiceMonitor` which will generate a ServiceMonitor for the application.
The service monitor requires the prometheus operator, in order to work. Once its created the operator will take care of monitoring the application.
> Introduce prometheus annotations

- .circleci/config.yml
- pom.xml
This is done because the examples don't respect -DskipTests
> feat: disable examples building by default

- annotations/generatoroptions-annotations/pom.xml
- annotations/generatoroptions-annotations/src/main/java/io/ap4k/generatoroptions/annotation/GeneratorOptions.java
- annotations/generatoroptions-annotations/src/main/java/io/ap4k/generatoroptions/handler/GeneratorOptionsHandler.java
- annotations/generatoroptions-annotations/src/main/java/io/ap4k/generatoroptions/processor/GeneratorOptionsProcessor.java
- annotations/generatoroptions-annotations/src/main/resources/javax.annotation.processing.Processor
- annotations/pom.xml
- core/src/main/resources/META-INF/services/javax.annotation.processing.Processor
- examples/spring-boot-with-fmp-on-kubernetes-example/pom.xml
- examples/spring-boot-with-fmp-on-kubernetes-example/src/main/java/io/ap4k/example/sbonkubernetes/Main.java
- starters/kubernetes/kubernetes-spring-starter/pom.xml
- starters/kubernetes/kubernetes-thorntail-starter/pom.xml
- starters/openshift/openshift-spring-starter/pom.xml
- starters/openshift/openshift-thorntail-starter/pom.xml
The fact that the module was in the core meant that it got executed
even when a project was only including the apt versions of annotations
> refactor: Extract GeneratorOptions into a separate module

- core/src/main/java/io/ap4k/project/BuildInfo.java
This is done to decouple the location of where the ap4k resources should
be written from where the build places resources.
In most cases the two would be the same, but there are cases (like the
upcoming Quarkus extensions where the two could be different).
This directory will be used later to read application configuration
for use in various Configurator classes
> feat: introduce applicationResourceOutputDir

- annotations/openshift-annotations/src/main/java/io/ap4k/openshift/decorator/AddRouteDecorator.java
- examples/source-to-image-example/pom.xml
- examples/source-to-image-example/src/main/java/io/ap4k/examples/s2i/Main.java
- examples/source-to-image-example/src/test/java/io/ap4k/examples/s2i/SourceToImageIT.java
There is no need to have `host` set in order for `Route` to work properly (FMP does not set it either or require the user to supply it)
> fix: Rationalize the handling of Route

- core/src/main/java/io/dekorate/processor/AbstractAnnotationProcessor.java
- frameworks/spring-boot/src/it/annotationless-yml/src/main/resources/application-kubernetes.yml
- frameworks/spring-boot/src/it/annotationless-yml/src/test/java/io/dekorate/annotationless/AnnotationLessTest.java
It would be very common to have both an `application` properties file and an `application-kubernetes` properties.  Right now only one can be used.  This would allow us to combine the properties in more than one file.
> Combine properties from all YAML and Properties files

- annotations/component-annotations/src/it/issue-276/pom.xml
- annotations/component-annotations/src/it/issue-276/src/main/java/io/dekorate/issue276/Controller.java
- annotations/component-annotations/src/it/issue-276/src/main/java/io/dekorate/issue276/DemoApplication.java
- annotations/component-annotations/src/it/issue-276/src/main/resources/application.properties
- annotations/component-annotations/src/it/issue-276/src/test/java/io/dekorate/issue276/Issue276Test.java
- annotations/component-annotations/src/main/java/io/dekorate/component/handler/ComponentHandler.java
- core/src/main/java/io/dekorate/utils/Labels.java
> Ensure that the name property of @ComponentApplication is applied

- core/src/main/java/io/dekorate/project/GradleInfoReader.java
- core/src/test/java/io/dekorate/project/GradleInfoReaderTest.java
- core/src/test/resources/gradle/gradle-with-settings/build.gradle
- core/src/test/resources/gradle/gradle-with-settings/settings.gradle
> fix (#309): readSettingsGradle() now ignores lines that don't contain

- annotations/knative-annotations/src/main/java/io/dekorate/knative/generator/KnativeApplicationGenerator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/KubernetesApplication.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/generator/KubernetesApplicationGenerator.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/handler/KubernetesHandler.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/hook/ScaleDeploymentHook.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/listener/KubernetesSessionListener.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/generator/OpenshiftApplicationGenerator.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/listener/OpenshiftSessionListener.java
- core/src/main/java/io/dekorate/hook/OrderedHook.java
- core/src/main/java/io/dekorate/hook/ResourceDeleteHook.java
- core/src/main/java/io/dekorate/hook/ResourcesApplyHook.java
- core/src/main/java/io/dekorate/kubernetes/config/ImageConfiguration.java
- frameworks/spring-boot/src/it/annotationless-yml/Dockerfile
- frameworks/spring-boot/src/it/annotationless-yml/src/main/resources/application.yml
application annotations.
Ever since we split build annotations from application annotations some properties were available to both kind of annotation. However, build annotations were not working correctly.
This pull request fixes build annotations and it makes sure that both kinds work (until we de-duplicate).
> fix (#352): Builds are now triggered both build service and

- examples/spring-boot-on-kubernetes-example/src/main/java/io/dekorate/example/sbonkubernetes/Main.java
- examples/spring-boot-with-gradle-on-kubernetes-example/src/main/java/io/dekorate/example/sbonkubernetes/Main.java
- examples/spring-boot-with-gradle-on-openshift-example/src/main/groovy/io/dekorate/example/sbonopenshift/Main.groovy
- frameworks/spring-boot/src/main/java/io/dekorate/spring/generator/SpringBootApplicationGenerator.java
At the moment, every example using Spring boot defaults to `livenessProbe` == `readinessProbe` == `/actuator/health` and that is typically a bad idea.
Liveness Probes responds to the question of when should I restart a container. Readiness Probes responds to the question of when should I start accepting traffic.
Making Liveness dependent on an external check, like other services or databases can cause a restart of all your containers when just a single external failure occurs.
For that reason, I suggest making the liveness probe defaults to `/actuator/info`
What are your thoughts?
Thanks,
Alberto
> Stop defaulting to /actuator/health on liveness probes

- pom.xml
Why?
- We don't need it and its a dependency not available in central.
- To avoid issues with donwstream project.
- To make things cleaner.
> chore: exclude com.sun.tools from all profiles.

- tests/test-cases.md
The intention here is to have a document that describes the test cases that we need to cover.
This is the first step.
The next step is to enrich this document as it currently just scratches the surface.
The following steps would be to move actual integration tests from the individual modules here and update the document to point to the actual tests.
> doc: document test cases dekorate needs to cover.

- .circleci/config.yml
- pom.xml
As we now have individual modules per tests, I'd rather use a different profile and keep them off releases to avoid polutting our public maven repo.
> refactor: Tests now use their own dedicated profile.

- annotations/docker-annotations/src/main/java/io/dekorate/docker/buildservice/DockerBuildServiceFactory.java
- annotations/jib-annotations/src/main/java/io/dekorate/jib/buildservice/JibBuildServiceFactory.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/generator/KnativeApplicationGenerator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/handler/KubernetesHandler.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/listener/KubernetesSessionListener.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/listener/OpenshiftSessionListener.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/buildservice/S2iBuildServiceFactory.java
- core/src/main/java/io/dekorate/AbstractKubernetesHandler.java
- core/src/main/java/io/dekorate/BuildServiceFactories.java
- core/src/main/java/io/dekorate/BuildServiceFactory.java
- core/src/main/java/io/dekorate/Configurators.java
- core/src/main/java/io/dekorate/config/AnnotationConfiguration.java
- core/src/main/java/io/dekorate/config/ConfigurationSupplier.java
- core/src/main/java/io/dekorate/config/PropertyConfiguration.java
- testing/core-junit/src/main/java/io/dekorate/testing/WithImageConfig.java
We recently added support for multple different image configurations (docker, jib, s2i).
Each config is meant to be used only in projects where its actually applicable.
For instance it doesn't make sense to use docker config, if no docker files are provided.
However, if the use has provided explicitly configuration for cases like this, we should consider it applicable no matter what.
> fix (#420): Explicit configuration is always considered applicable.

- core/src/main/java/io/dekorate/kubernetes/config/ImageConfiguration.java
Image configuration field in `@DockerBuild` was being ignored
- https://github.com/fabric8io/fabric8-maven-plugin/issues/1483
- https://github.com/fabric8io/fabric8-maven-plugin/pull/1767
> fix: Image field ignored in ImageConfiguration

- .circleci/config.yml
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/buildservice/S2iBuildService.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/decorator/AddBuildConfigResourceDecorator.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/decorator/AddOutputImageStreamResourceDecorator.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/generator/S2iBuildGenerator.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/handler/S2iHanlder.java
- testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/OpenshiftExtension.java
- tests/issue-442-build-config-name/pom.xml
- tests/issue-442-build-config-name/src/test/java/io/dekorate/examples/kuberentes/Issue442BuildConfigNameIT.java
- tests/issue-442-build-config-name/src/test/java/io/dekorate/examples/kuberentes/Issue442BuildConfigNameIntegrationTest.java
- tests/issue-442-build-config-name/src/test/java/io/dekorate/examples/kuberentes/Issue442BuildConfigNameTest.java
resource. S2i resources aligned with the rest of the converntions. Added tests.
This pull request is meant to do the following:
- Have openshift resources correctly refer to s2i resources  (imagestreams, etc).
- Have openshift shutdown hooks, correctly identify s2i names.
- Have s2i build service retain imagestreams (workaround ci related issues).
- Add integration test for the above.
- Deal with circleci issues and missing s2i-java tags.
> fix (#442): S2iBuildService now uses whatever name was given to the

- annotations/knative-annotations/src/main/java/io/dekorate/knative/generator/DefaultKnativeApplicationGenerator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/generator/KnativeApplicationGenerator.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/generator/DefaultKubernetesApplicationGenerator.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/generator/KubernetesApplicationGenerator.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/generator/DefaultOpenshiftApplicationGenerator.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/generator/OpenshiftApplicationGenerator.java
- core/src/main/java/io/dekorate/kubernetes/configurator/ApplyImagePullSecretConfiguration.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddImagePullSecretDecorator.java
This pr allows setting image pull secrets for kubernets, openshift and knative via: `dekorate.image-pull-secrets=<my secret>`.
This is needed for tekton support.
> feat: Support image pull secrets via cli

- core/src/main/java/io/dekorate/LoggerFactory.java
- core/src/main/java/io/dekorate/Session.java
We need to do this because otherwise other loggers won't
use the same logger
> Make all loggers use the one created with the session

- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/decorator/AddBuildConfigResourceDecorator.java
- examples/spring-boot-on-openshift-example/src/test/java/io/dekorate/example/sbonopenshift/SpringBootOnOpenshiftTest.java
This pull request introduces a slightly smarter way to find the version to use when creating buildconfig.
Instead of just using `latest` we use the `config.version` which is aware of the actual project version.
> fix: BuildConfig is in sync with DeploymentConfig

- core/src/main/java/io/dekorate/utils/Gradle.java
- core/src/main/java/io/dekorate/utils/Maven.java
It seems that in some cases the version check command may fail. It's extremely hard to troubleshoot why and that makes for a horrible user experience.
If we can't determine the build tool version, we should assume it. 
We already provide properties for expliclitly setting the version, so users not happy with the fallback version can always change that.
> fix: maven & gradle utils return fallback version

- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/annotation/TektonApplication.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddPvcToPipelineRunDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddPvcToTaskRunDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddWorkspaceToPipelineTaskDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/handler/TektonHandler.java
- core/src/main/java/io/dekorate/kubernetes/annotation/AccessMode.java
- core/src/main/java/io/dekorate/kubernetes/annotation/PersistentVolumeClaim.java
- examples/pom.xml
- examples/spring-boot-with-tekton-and-m2-pvc-example/Dockerfile
- examples/spring-boot-with-tekton-and-m2-pvc-example/pom.xml
- examples/spring-boot-with-tekton-and-m2-pvc-example/readme.md
- examples/spring-boot-with-tekton-and-m2-pvc-example/src/main/java/io/dekorate/example/sbonkubernetes/Controller.java
- examples/spring-boot-with-tekton-and-m2-pvc-example/src/main/java/io/dekorate/example/sbonkubernetes/Main.java
- examples/spring-boot-with-tekton-and-m2-pvc-example/src/main/resources/application.properties
- examples/spring-boot-with-tekton-and-m2-pvc-example/src/test/java/io/dekorate/example/sbonkubernetes/SpringBootWithTektonTest.java
- examples/spring-boot-with-tekton-example/src/main/resources/application.properties
Fixes #499 
The pull request:
- introduces new `@PersistentVolumeClain` annotation for configuring PVCs.
- tekton configuration reuses `@PersistentVolumeClaim` to setup `source and `m2` workspaces.
- adds m2 examples & tests.
> feat (#499): Maven workspace is now working

- annotations/knative-annotations/src/test/java/io/dekorate/knative/generator/KnativeApplicationGeneratorTest.java
- annotations/kubernetes-annotations/src/test/java/io/dekorate/kubernetes/generator/KubernetesApplicationGeneratorTest.java
- annotations/openshift-annotations/src/test/java/io/dekorate/openshift/generator/OpenshiftApplicationGeneratorTest.java
- annotations/option-annotations/src/main/java/io/dekorate/option/annotation/GeneratorOptions.java
- annotations/option-annotations/src/main/java/io/dekorate/option/generator/DefaultOptionsGenerator.java
- annotations/option-annotations/src/main/java/io/dekorate/option/generator/JvmOptionsGenerator.java
- annotations/option-annotations/src/main/java/io/dekorate/option/generator/OptionsGenerator.java
- annotations/option-annotations/src/main/resources/META-INF/services/io.dekorate.Generator
- annotations/tekton-annotations/src/test/java/io/dekorate/tekton/generator/TektonApplicationGeneratorTest.java
- core/src/main/java/io/dekorate/SessionWriter.java
- core/src/main/java/io/dekorate/processor/AbstractAnnotationProcessor.java
- core/src/main/java/io/dekorate/processor/AptWriter.java
- core/src/main/java/io/dekorate/processor/SimpleFileWriter.java
- core/src/main/java/io/dekorate/project/Project.java
- testing/core-junit/src/main/java/io/dekorate/testing/WithImageConfig.java
- testing/core-junit/src/main/java/io/dekorate/testing/WithProject.java
- testing/kubernetes-junit/src/main/java/io/dekorate/testing/kubernetes/WithKubernetesConfig.java
- testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/WithOpenshiftConfig.java
This pull request makes it possible to write manifests outside of target by leveraging the property `dekorate.options.output-path`. 
The property was already available via annotations, but now it can be set from .yml/.property files too.
Also, this pull request moves geenrated metadata in they own special place `../.dekorate` relative to output classes directory.
> Allow generating manifests outside target

- core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java
- tests/issue-507-spring-boot-server-port/pom.xml
- tests/issue-507-spring-boot-server-port/src/main/java/io/dekorate/annotationless/DemoApplication.java
- tests/issue-507-spring-boot-server-port/src/main/java/io/dekorate/annotationless/HelloController.java
- tests/issue-507-spring-boot-server-port/src/main/resources/application.properties
- tests/issue-507-spring-boot-server-port/src/test/java/io/dekorate/annotationless/Issue507Test.java
- tests/issue-507-unamed-port/pom.xml
- tests/issue-507-unamed-port/src/main/java/io/dekorate/annotationless/DemoApplication.java
- tests/issue-507-unamed-port/src/main/java/io/dekorate/annotationless/HelloController.java
- tests/issue-507-unamed-port/src/main/resources/application.properties
- tests/pom.xml
Fixes: #507 
Also adds test cases, to verify the fix and an additional test to verify `server.port` support.
> fix (#507) Prevent NPE when port is not named. Add tests.

- core/src/main/java/io/dekorate/kubernetes/decorator/AddEnvVarDecorator.java
- tests/issue-517-exclude-optional/pom.xml
- tests/issue-517-exclude-optional/src/main/java/io/dekorate/annotationless/DemoApplication.java
- tests/issue-517-exclude-optional/src/main/java/io/dekorate/annotationless/HelloController.java
- tests/issue-517-exclude-optional/src/main/resources/application.properties
- tests/issue-517-exclude-optional/src/test/java/io/dekorate/kubernetes/Issue517Test.java
- tests/pom.xml
Fixes #517 
As it was not possible to address the issue on Serialization level, we address just the case with `optional` on decorator level.
> fix (#517) optional is now excluded for env var source and key selector.

- examples/thorntail-on-kubernetes-example/src/test/java/io/dekorate/example/thorntailonkubernetes/ThorntailOnKubernetesIT.java
- examples/thorntail-on-openshift-example/src/test/java/io/dekorate/example/thorntailonopenshift/ThorntailOnOpenshiftIT.java
Fixes: #519
The main changes of the pull request are the following:
- Generators now return config class instead of annotation class.
- Code that references annotations moved from `Generator` class to `AnnotationProcessor` classes
> Decouple annotations from logic

- release.sh
- scripts/ChangeVersion.java
Resolves: #538  
The pull request updates the release script so that it always updates dekorate version in our readme.md.
The script invokes a jbang script that parses line by line and changes the version in all `dependency` and `path` elements that have `io.dekorate` as `groupId`.
> doc(#538) Automatically bump release version in docs

- readme.md
According to the docs: https://quarkus.io/guides/deploying-to-kubernetes#kubernetes the folder is target/kubernetes
> docs: fix Quarkus kubernetes target folder

- .circleci/config.yml
This pull request configures builds to log into docker.io, so that images can be pushed to an external registry.
> Configure circleci to perform docker login

- core/src/main/java/io/dekorate/utils/Serialization.java
Currently, when outputting YAML, int values that are in strings, don't have quotes, causing issues
when the generated manifests are applied
Relates to: 
https://github.com/quarkusio/quarkus/issues/11134
https://github.com/quarkusio/quarkus/issues/11431
> Make sure that YAML output doesn't mess with "int" types

- annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/handler/ComponentHandler.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/handler/KnativeHandler.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/handler/KubernetesHandler.java
- annotations/openshift-annotations/pom.xml
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/AddLabelToDeploymentConfigSelectorDecorator.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/DeploymentConfigSelectorDecoratorFactory.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/RemoveLabelFromDeploymentConfigSelectorDecorator.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java
- annotations/openshift-annotations/src/main/resources/META-INF/services/io.dekorate.SelectorDecoratorFactory
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/decorator/AddBuildConfigResourceDecorator.java
- core/src/main/java/io/dekorate/AbstractKubernetesHandler.java
- core/src/main/java/io/dekorate/SelectorDecoratorFactories.java
- core/src/main/java/io/dekorate/SelectorDecoratorFactory.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddLabelDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddLabelToServiceSelectorDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddToMatchingLabelsDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddToSelectorDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveFromMatchingLabelsDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveFromSelectorDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveLabelDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveLabelFromServiceSelectorDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ServiceSelectorDecoratorFactory.java
- core/src/main/java/io/dekorate/utils/Metadata.java
- core/src/main/resources/META-INF/services/io.dekorate.SelectorDecoratorFactory
- examples/halkyon-example/src/test/java/io/dekorate/examples/ComponentSpringBootExampleTest.java
The pull request introduces a more fine grained control over labels and selectors.
Up until now, labels and selectors were `hardcoded` in the base resources created by dekorate.
- Adding or removing labels didn't have any impact on selectors.
- Labels were not added in the provided resources.
- There was no single way to decorate selectors.
The pull request changes all three items above:
- Added and SPI for managing selector decorators
- Added a generic add/remove selector decorator.
- Labels are now added via decorators
> feat (#609): Allow adding/removing labels to/from selectors

- annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/handler/ComponentHandler.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/decorator/ApplyDeploymentStrategyDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddToMatchingLabelsDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddToSelectorDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveFromMatchingLabelsDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveFromSelectorDecorator.java
> 0.12.x selector fix

- annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/adapter/ComponentConfigAdapter.java
- annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/handler/ComponentHandler.java
- annotations/knative-annotations/src/test/java/io/dekorate/knative/config/KnativeConfigTest.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/handler/KubernetesHandler.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/AddRouteDecorator.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java
- annotations/openshift-annotations/src/test/java/io/dekorate/openshift/config/OpenshiftConfigTest.java
- core/src/main/java/io/dekorate/AbstractKubernetesHandler.java
- core/src/main/java/io/dekorate/kubernetes/annotation/Annotation.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddAnnotationDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddLabelDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java
- core/src/main/java/io/dekorate/utils/Labels.java
- core/src/test/java/io/dekorate/kubernetes/decorator/AddAnnotationDecoratorTest.java
- pom.xml
- tests/feat-553-ingress-annotations/Dockerfile
- tests/feat-553-ingress-annotations/pom.xml
- tests/feat-553-ingress-annotations/src/main/java/io/dekorate/annotationless/DemoApplication.java
- tests/feat-553-ingress-annotations/src/main/resources/application.yml
- tests/feat-553-ingress-annotations/src/test/java/io/dekorate/annotationless/Feat533Test.java
- tests/pom.xml
Resolves: #553 
This pull request introduces a new fields `kinds` on `@Label` and `@Annotation`. The use of these fields will limit the application of Labels/Annotations only to the listed kinds. If omitted, all kinds are asumed.
> Feat 553 resource level annotations

- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveFromMatchingLabelsDecorator.java
Currently RemoveFromMatchingLabelsDecorator does not work properly. This pull request addresses that.
> fix: ordering issue with matchLabels decorators

- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyLimitsMemoryDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyRequestsMemoryDecorator.java
- tests/feat-429-container-resources/src/test/java/io/dekorate/annotationless/Feat429Test.java
As stated here : https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
The generated resources for memory limits/requests should be "memory" and not "mem"
Signed-off-by: Vincent Sourtin <sourin-v@bridgestone-bae.com>
> Kubernetes Container Resources

- annotations/halkyon-annotations/src/main/java/io/dekorate/halkyon/handler/ComponentHandler.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java
- core/src/main/java/io/dekorate/AbstractKubernetesHandler.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddAnnotationDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddLabelDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveAnnotationDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveLabelDecorator.java
resources (vs all resources).
As we are incosistnent on where we apply label and annotation decorator, this pull request limits that to just named resources. In other words resources directly generated by us.
> refactor: Labels and annotations are now only added to named

- CONTRIBUTING.md
Contributing.md is standard for github repositories. I did not want to move file from original assets folder as there is value of keeping the docs in the same folder. That is why we adding contributing guide but linking to the other document.
> chore: Add link do contributing documentation

- annotations/crd-annotations/src/main/java/io/dekorate/crd/util/JsonSchema.java
This trivial PR fixes a typo in the JSON integer schema that is the cause of a malformed CRD using "ineger" instead of "integer" type.
> Fixed integer schema typo

- core/src/main/java/io/dekorate/utils/Exec.java
Finally!
Should we add some test? I'll let you take a look @iocanel, let me know if something is needed
> fix: unlock mvnDebug process by removing the debug env vars

- annotations/docker-annotations/src/main/java/io/dekorate/docker/config/DefaultDockerBuildConfigGenerator.java
- annotations/docker-annotations/src/main/java/io/dekorate/docker/config/DockerBuildConfigGenerator.java
- annotations/jib-annotations/src/main/java/io/dekorate/jib/config/DefaultJibBuildConfigGenerator.java
- annotations/jib-annotations/src/main/java/io/dekorate/jib/config/JibBuildConifgGenerator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/config/DefaultKnativeConfigGenerator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/config/KnativeConfigGenerator.java
- annotations/knative-annotations/src/test/java/io/dekorate/knative/config/KnativeConfigGeneratorTest.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/config/DefaultKubernetesConfigGenerator.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/config/KubernetesConfigGenerator.java
- annotations/kubernetes-annotations/src/test/java/io/dekorate/kubernetes/config/KubernetesConfigGeneratorTest.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/config/DefaultOpenshiftConfigGenerator.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/config/OpenshiftConfigGenerator.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/config/DefaultS2iBuildConfigGenerator.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/config/S2iBuildConfigGenerator.java
- annotations/servicebinding-annotations/src/main/java/io/dekorate/servicebinding/config/DefaultServiceBindingConfigGenerator.java
- annotations/servicebinding-annotations/src/main/java/io/dekorate/servicebinding/config/ServiceBindingConfigGenerator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/config/DefaultTektonConfigGenerator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/config/TektonConfigGenerator.java
- annotations/tekton-annotations/src/test/java/io/dekorate/tekton/config/TektonConfigGeneratorTest.java
- core/src/main/java/io/dekorate/ConfigurationRegistry.java
- core/src/main/java/io/dekorate/DefaultCoordinates.java
- core/src/main/java/io/dekorate/Logger.java
- core/src/main/java/io/dekorate/Session.java
- core/src/main/java/io/dekorate/logger/AnsiLogger.java
- core/src/main/java/io/dekorate/logger/AptLogger.java
- core/src/main/java/io/dekorate/utils/Strings.java
- examples/kubernetes-with-custom-image-name-example/src/main/java/io/dekorate/example/Main.java
- readme.md
Resolves: #727
The pull request does the following:
- Separates addition of configurers from configuration (allows keeping track of what explciitly/implictly configured).
- Apply single application configuration to image configuration with missing explicit values for group, name & version.
- Throw error when there are conficting explict values
> Align group, name and version

- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/KubernetesApplication.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/manifest/KubernetesManifestGenerator.java
- tests/issue-331-annotation-combined-with-properties/src/main/java/io/dekorate/annotationless/DemoApplication.java
- tests/issue-331-annotation-combined-with-properties/src/main/resources/application.properties
- tests/issue-331-annotation-combined-with-properties/src/test/java/io/dekorate/annotationless/Issue331Test.java
Related to #706 
This is not completely fixed but contains some needed code. This PR fixes the hard code for replicas, improve the test and remove default value for replicas in k8s application config
> Configuration for primitives is not taken into account, default value has higher priority

- core/src/main/java/io/dekorate/utils/Maven.java
> fix: parse Maven version in an ANSI escape sequence safe way

- core/src/main/java/io/dekorate/logger/AnsiLogger.java
Instead of throw an `IllegalStateException` exception we could log an `error` msg and swap to std out.
Related issue: https://github.com/quarkusio/quarkus/issues/15953
> Invalid logger breaks current application flow

- testing/kubernetes-junit/src/main/java/io/dekorate/testing/kubernetes/KubernetesExtension.java
- testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/OpenshiftExtension.java
When using `@KubernetesIntegrationTest(deployEnabled = false)` or `@OpenShiftIntegrationTest(deployEnabled = false)` means that the test framework did not deploy the resources, but they were deployed before running the test. 
The problem is that regardless if the testing deployed the application or not, it's always deleting the resources.
With these changes, the test framework will only delete the resources if and only if the test framework deployed them.
> Testing: Don't delete resources if deploy was disabled

- testing/kubernetes-junit/src/main/java/io/dekorate/testing/kubernetes/WithKubernetesResources.java
- testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/WithOpenshiftResources.java
Both Kubernetes and OpenShift resources should use the same logic to retrieve the resources to deploy.
> Testing: Fix resolve of generated resources for Kubernetes

- readme.md
The Dekorate testing framework supports multi-module projects either using [the OpenShift JUnit 5 extension](#openshift-extension-for-junit5) or using [the Kubernetes JUnit 5 extension](#kubernetes-extension-for-junit5).
A multi-module project consist of multiple modules, all using Dekorate to generate the cluster manifests and a `tests` module that will run the integration tests:
```
multi-module-parent
└───module-1
└───module-2
└───tests
```
In the `tests` module, we can now specify the location of the additional modules via the field `additionalModules` which is part of the `@OpenshiftIntegrationTest` and `@KubernetesIntegrationTest` annotations:
```java
@OpenshiftIntegrationTest(additionalModules = { "../module-1", "../module-2" })
class SpringBootForMultipleAppsOnOpenshiftIT { …
```
> Add documentation about Multi Module testing

- annotations/docker-annotations/src/main/java/io/dekorate/docker/buildservice/DockerBuildServiceFactory.java
- annotations/jib-annotations/src/main/java/io/dekorate/jib/buildservice/JibBuildServiceFactory.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/buildservice/S2iBuildServiceFactory.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/manifest/S2iManifestGenerator.java
- testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/OpenshiftExtension.java
- testing/openshift-junit/src/main/java/io/dekorate/testing/openshift/WithOpenshiftConfig.java
- tests/issue-821-docker-build-on-ocp-test/Dockerfile
- tests/issue-821-docker-build-on-ocp-test/pom.xml
- tests/issue-821-docker-build-on-ocp-test/src/main/java/io/dekorate/example/Controller.java
- tests/issue-821-docker-build-on-ocp-test/src/main/java/io/dekorate/example/Main.java
- tests/issue-821-docker-build-on-ocp-test/src/main/resources/application.properties
- tests/issue-821-docker-build-on-ocp-test/src/test/java/io/dekorate/example/Issue821IT.java
- tests/pom.xml
The property `dekorate.docker.enabled` was being ignored by the test framework.
It also fixes the `jib` build.
Fix https://github.com/dekorateio/dekorate/issues/821
> Testing: Docker build should not be used if it's disabled

- annotations/knative-annotations/src/main/java/io/dekorate/knative/config/KnativeAdditionalResourcesProvider.java
- annotations/knative-annotations/src/main/resources/META-INF/services/io.dekorate.config.AdditionalResourcesProvider
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/config/KubernetesAdditionalResourcesProvider.java
- annotations/kubernetes-annotations/src/main/resources/META-INF/services/io.dekorate.config.AdditionalResourcesProvider
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/config/OpenshiftAdditionalResourcesProvider.java
- annotations/openshift-annotations/src/main/resources/META-INF/services/io.dekorate.config.AdditionalResourcesProvider
- core/src/main/java/io/dekorate/apt/DekorateProcessor.java
- core/src/main/java/io/dekorate/config/AdditionalResourcesLocator.java
- core/src/main/java/io/dekorate/config/AdditionalResourcesProvider.java
- core/src/main/java/io/dekorate/config/DekorateProfileAdditionalResourcesProvider.java
- core/src/main/resources/META-INF/services/io.dekorate.config.AdditionalResourcesProvider
- examples/pom.xml
- examples/spring-boot-on-openshift-with-dekorate-profile-example/pom.xml
- examples/spring-boot-on-openshift-with-dekorate-profile-example/src/main/java/io/dekorate/example/Controller.java
- examples/spring-boot-on-openshift-with-dekorate-profile-example/src/main/java/io/dekorate/example/Main.java
- examples/spring-boot-on-openshift-with-dekorate-profile-example/src/main/resources/application-foo.properties
- examples/spring-boot-on-openshift-with-dekorate-profile-example/src/test/java/io/dekorate/example/SpringBootOnOpenshiftIT.java
- examples/spring-boot-on-openshift-with-dekorate-profile-example/src/test/java/io/dekorate/example/SpringBootOnOpenshiftTest.java
- examples/spring-boot-on-openshift-with-ocp-properties-example/pom.xml
- examples/spring-boot-on-openshift-with-ocp-properties-example/src/main/java/io/dekorate/example/Controller.java
- examples/spring-boot-on-openshift-with-ocp-properties-example/src/main/java/io/dekorate/example/Main.java
- examples/spring-boot-on-openshift-with-ocp-properties-example/src/main/resources/application-openshift.properties
- examples/spring-boot-on-openshift-with-ocp-properties-example/src/test/java/io/dekorate/example/SpringBootOnOpenshiftIT.java
- frameworks/spring-boot/src/main/java/io/dekorate/spring/apt/SpringBootApplicationProcessor.java
- frameworks/thorntail/src/main/java/io/dekorate/thorntail/ThorntailProcessor.java
- readme.md
New order of properties file to use:
1. Annotations
2. `application.properties`
3. `application.yaml`
4. `application.yml`
Then,  it will use the properties file depending on the active Dekorate dependencies in use. For example, if we're using the dependency `io.dekorate:kubernetes-annotations`, then:
1. `application-kubernetes.properties`
2. `application-kubernetes.yaml`
3. `application-kubernetes.yml`
| Note that only the `openshift`, `kubernetes` and `knative` modules are providing additional properties files.
Then, for Spring Boot applications, it will also take into account the Spring property `spring.profiles.active` if set:
1. `application-${spring.profiles.active}.properties`
2. `application-${spring.profiles.active}.yaml`
3. `application-${spring.profiles.active}.yml`
Finally, if …
> Support configuration based on spring/dekorate profiles, and components

- core/src/main/java/io/dekorate/utils/Serialization.java
At the moment, the auto-generated file `kubernetes.json` looks like:
```json
{ object 1}{ object 2}{ object 3}
```
Which is not well formatted. This PR fixes this and produces the JSON file in the right format:
```json
[{ object 1}, 
{ object 2},
{ object 3}]
```
> Fix JSON auto generated files

- frameworks/spring-boot/src/main/java/io/dekorate/spring/generator/SpringBootApplicationGenerator.java
From Spring Boot 2.3, the `/actuator/info` endpoint which is used by the liveness probe, will only be exposed if and only if there is data to present (or it's forced by using `management.endpoints.web.exposure.include=info`).
Moreover, from Spring Boot 2.3, we should use the health liveness / readiness endpoints.
> Spring Boot: Change default actuator liveness/readiness probes

- core/src/main/java/io/dekorate/utils/Git.java
- core/src/test/java/io/dekorate/utils/GitTest.java
- core/src/test/resources/git-sub/git/config
The parsing of git config in the `Git.getRemotes` now properly ignores submodule references.
Previously, a any submodule sections would add a null keyed entry to the hash map. Aside from _not_ being a remote, it causes `DekorateException`s on output with the message "JSON doesn't allow `null` as a map key".
> Fix parsing in `Git.getRemotes` to ignore submodules

- .github/publish-docs.sh
- .github/set-version.sh
- .github/workflows/website.yml
The github action triggers on a tag push. It will set the correct version in the [file](https://github.com/dekorateio/dekorate/blob/9d56563ec00d087e1e055a6a690f36deb6f3db90/docs/_data/project.yml#L4-L3) used by Jekyll for gathering the Dekorate version in the whole site.
Fixes #860
> refactor: fix website job

- docs/_data/project.yml
Quick PR to update manually the Dekorate version in site and docs. FYI next time it will be done by [this job](https://github.com/dekorateio/dekorate/blob/f6f1350d65510ed302646832460338d0a7c96fbb/.github/workflows/website.yml#L13) that triggers when a new tag is pushed.
> refactor: set correct version for docs

- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyAnnotationsToServiceTemplate.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyGlobalContainerConcurrencyDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalAutoscalingClassDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalAutoscalingMetricDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalAutoscalingTargetDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyLocalTargetUtilizationPercentageDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyMaxScaleDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyMinScaleDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/manifest/KnativeManifestGenerator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddConfigMapResourceProvidingDecorator.java
- core/src/main/java/io/dekorate/utils/Ports.java
- examples/knative-example/src/main/java/io/dekorate/example/Main.java
- examples/knative-example/src/test/java/io/dekorate/example/KnativeExampleTest.java
- tests/feat-575-knative-local-autoscaling/src/test/java/io/dekorate/knative/Feat575LocalAutoscalingTest.java
- tests/issue-586-knative-scale-bounds/src/test/java/io/dekorate/knative/Issue586ScaleBoundsTest.java
The Knative generated manifests have the following issues:
- The generated `config-autoscaler` configmap does not set the namespace which should always be `knative-serving` (see for example https://knative.dev/docs/serving/autoscaling/scale-to-zero/#enable-scale-to-zero).
- Some properties do add the annotations at Knative service metadata level, and it should add them at Knative service spec template metadata level.
- The property `dekorate.knative.global-auto-scaling.containerConcurrency` (hard limit option) wrongly uses the `config-autoscaler` configmap and it should use `config-defaults` configmap (see https://knative.dev/docs/serving/autoscaling/concurrency/#hard-limit)
Fix https://github.com/dekorateio/dekorate/issues/869
> Knative: Fix generated resources

- docs/documentation/jaeger.md
The URL to Jaeger example was pointing to a resource that does exist.
> docs: Fixed small typo in the URL to Jaeger example

- annotations/knative-annotations/src/main/java/io/dekorate/knative/annotation/KnativeApplication.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/KubernetesApplication.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/annotation/OpenshiftApplication.java
- assets/design.md
- core/src/main/java/io/dekorate/AbstractKubernetesManifestGenerator.java
- core/src/main/java/io/dekorate/kubernetes/adapter/ContainerAdapter.java
- core/src/main/java/io/dekorate/kubernetes/annotation/Base.java
- core/src/main/java/io/dekorate/kubernetes/annotation/Container.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddStartupProbeDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/RemoveProbesFromInitContainerDecorator.java
- docs/documentation/design.md
- examples/knative-example/src/main/java/io/dekorate/example/Main.java
- examples/knative-example/src/test/java/io/dekorate/example/KnativeExampleTest.java
- examples/vertx-on-kubernetes-example/pom.xml
- examples/vertx-on-kubernetes-example/src/main/resources/application.properties
- examples/vertx-on-kubernetes-example/src/test/java/io/dekorate/example/VertxTest.java
- examples/vertx-on-openshift-example/pom.xml
- examples/vertx-on-openshift-example/src/main/resources/application.properties
- examples/vertx-on-openshift-example/src/test/java/io/dekorate/example/VertxTest.java
The kubelet uses startup probes to know when a container application has started. If such a probe is configured, it disables liveness and readiness checks until it succeeds, making sure those probes don't interfere with the application startup. This can be used to adopt liveness checks on slow starting containers, avoiding them getting killed by the kubelet before they are up and running.
```yaml
startupProbe:
httpGet:
path: /healthz
port: liveness-port
failureThreshold: 30
periodSeconds: 10
```
More context in [kubernetes.io/startup-probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).
Fix https://github.com/dekorateio/dekorate/issues/854
> Support Startup Probes for Kubernetes, Openshift and Knative

- annotations/prometheus-annotations/src/main/java/io/dekorate/prometheus/client/dsl/internal/ServiceMonitorOperationsImpl.java
- pom.xml
All changes: https://github.com/fabric8io/kubernetes-client/compare/v5.10.0...v5.12.1
We need to bump the Kubernetes Client to the most recent version to support gRPC actions (see https://github.com/dekorateio/dekorate/issues/857)
> Update Kubernetes Client dependency to most recent version 5.12.1

- examples/knative-example/src/test/java/io/dekorate/example/KnativeExampleTest.java
- examples/vertx-on-kubernetes-example/src/main/resources/application.properties
- examples/vertx-on-kubernetes-example/src/test/java/io/dekorate/example/VertxTest.java
- examples/vertx-on-openshift-example/src/main/resources/application.properties
- tests/feat-642-knative-traffic-splitting/pom.xml
- tests/feat-knative-probes/pom.xml
- tests/feat-knative-probes/src/main/java/io/dekorate/example/Controller.java
- tests/feat-knative-probes/src/main/java/io/dekorate/example/Main.java
- tests/feat-knative-probes/src/test/java/io/dekorate/example/KnativeExampleTest.java
- tests/feat-kubernetes-probes/pom.xml
- tests/feat-kubernetes-probes/src/main/java/io/dekorate/example/Main.java
- tests/feat-kubernetes-probes/src/main/resources/application.properties
- tests/feat-kubernetes-probes/src/test/java/io/dekorate/example/VertxTest.java
- tests/feat-openshift-probes/pom.xml
- tests/feat-openshift-probes/src/main/java/io/dekorate/example/Main.java
- tests/feat-openshift-probes/src/main/resources/application.properties
- tests/feat-openshift-probes/src/test/java/io/dekorate/example/VertxTest.java
- tests/pom.xml
In this PR: https://github.com/dekorateio/dekorate/pull/875, we added the Probe coverage under the examples, where it should go under the tests modules.
> Move Probe tests from `examples` to `tests`

- assets/config.md
- core/src/main/java/io/dekorate/kubernetes/annotation/Probe.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AbstractAddProbeDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddLivenessProbeDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddReadinessProbeDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddStartupProbeDecorator.java
- docs/configuration-guide.md
- tests/feat-857-kubernetes-grpc-probes/pom.xml
- tests/feat-857-kubernetes-grpc-probes/src/main/java/io/dekorate/example/Controller.java
- tests/feat-857-kubernetes-grpc-probes/src/main/java/io/dekorate/example/Main.java
- tests/feat-857-kubernetes-grpc-probes/src/main/resources/application.properties
- tests/feat-857-kubernetes-grpc-probes/src/test/java/io/dekorate/example/GRPCProbesExampleTest.java
- tests/pom.xml
See feature request description in https://github.com/dekorateio/dekorate/issues/857
Fix https://github.com/dekorateio/dekorate/issues/857
> Support gRPC probes for Kubernetes, Openshift and Knative

- core/src/main/java/io/dekorate/Logger.java
- core/src/main/java/io/dekorate/ResourceRegistry.java
- core/src/main/java/io/dekorate/Session.java
- core/src/main/java/io/dekorate/utils/Development.java
- docs/documentation/debugging-logging.md
Added a new system property `dekorate.version` to turn on the full verbose mode to troubleshoot issues at the Dekorate generation of manifests. This mode will print:
- The configuration registries applied
- The decorators applied
Example:
```
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ spring-boot-on-kubernetes-example ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/jcarvaja/sources/dekorate/examples/spring-boot-on-kubernetes-example/target/classes
[INFO] Found @KubernetesApplication on: io.dekorate.example.Main
[INFO] Initializing dekorate session.
[INFO] Found Spring web annotation!
[INFO] Found @SpringBootApplication on: io.dekorate.example.Main
[INFO] Generating manifests.
[INFO] Using the configuration registry …
```
> Improve logging message to list: Configurators, Suppliers

- .github/workflows/integration-tests.yml
This caused by https://github.com/actions/runner/issues/449
See this comment that explains why it started failing now: https://github.com/actions/runner/issues/449#issuecomment-1058348592
> fix: use current date to cache mvn repo

- docs/documentation/kubernetes.md
- readme.md
Just stumbled upon this typo today when I tried to copy&paste stuff from the documentation. ;-)
> Fix typo: dekoarate->dekorate

- annotations/helm-annotations/pom.xml
Adding the model sources in the noapt classifier is necessary to overwrite the provided configuration.
> feat: include helm model in helm annotations in noapt classifier

- annotations/helm-annotations/pom.xml
Fix this issue: When using the helm extension with the `noapt` classifier, it's failing because the listener is missing.
> fix: helm - update pom configuration for noapt and processors

- .github/workflows/checks.yml
This is because some links are not available until they are available in the main branch.
Related failure that we'll about with this change: https://github.com/dekorateio/dekorate/runs/6290448335?check_suite_focus=true
> fix: run the checks job on push, instead of in pull requests

- .github/workflows/build.yml
- .github/workflows/integration-tests-with-dockerio.yml
- .github/workflows/integration-tests.yml
- annotations/docker-annotations/src/main/java/io/dekorate/docker/annotation/DockerBuild.java
- core/src/main/java/io/dekorate/kubernetes/configurator/ApplyBuildToImageConfiguration.java
- docs/documentation/docker-build-hook.md
- docs/documentation/junit-extensions.md
- examples/spring-boot-on-kubernetes-example/readme.md
- examples/spring-boot-on-kubernetes-with-jib-custom-registry-example/readme.md
- examples/spring-boot-on-kubernetes-with-jib-example/readme.md
- examples/spring-boot-on-kubernetes-with-sbo-example/readme.md
- examples/spring-boot-on-openshift-example/src/test/java/io/dekorate/example/SpringBootOnOpenshiftTest.java
- examples/spring-boot-with-tekton-and-m2-pvc-example/readme.md
- examples/spring-boot-with-tekton-example/readme.md
- readme.md
- tests/issue-963-docker-system-properties/Dockerfile
- tests/issue-963-docker-system-properties/pom.xml
- tests/issue-963-docker-system-properties/src/main/java/io/dekorate/example/Main.java
- tests/issue-963-docker-system-properties/src/main/resources/application.yml
- tests/issue-963-docker-system-properties/src/test/java/io/dekorate/example/Issue963Test.java
- tests/pom.xml
Additionally, I've changed the annotation `@EnableDockerBuild` to `@DockerBuild` that was renamed in Dekorate 2.x.
Fix https://github.com/dekorateio/dekorate/issues/963
> fix: populate Dekorate docker group and version from system properties

- docs/_includes/home-hero-band.html
- docs/_layouts/base.html
For example, the `Dekorate 2.9.3` text was displaying an anchor what was not expected to have.
I've added a CSS class with name `no-anchors`, so we can use it to skip the anchors in other places.
> docs: fix anchors in the index page

- docs/configuration-guide.md
The probe table is not correctly displayed in the site: https://dekorate.io/configuration-guide/#probe
This PR fixes this issue.
> docs: fix probe section in the configuration guide

- annotations/helm-annotations/src/main/java/io/dekorate/helm/util/HelmExpressionParser.java
- annotations/helm-annotations/src/test/java/io/dekorate/helm/util/HelmExpressionParserTest.java
- docs/documentation/helm.md
- Wildcard: map properties at any level
If we want to map a property that is placed at a very depth level, for example, the `containerPort` property:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: example
spec:
replicas: 3
selector:
matchLabels:
app.kubernetes.io/name: example
template:
metadata:
app.kubernetes.io/name: example
spec:
containers:
- env:
- name: KUBERNETES_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
name: example
ports:
- containerPort: 8080 // we want to map this property!
name: http
protocol: TCP
```
If we want to map the property `containerPort`, we would need to write all the parent properties as in:
```
dekorate.helm.values[0].paths=spec.template.spec.containers.ports.containerPort
```
And what about if the `containerPort` property is at …
> helm: support of path expressions with wildcard

- annotations/docker-annotations/src/main/java/io/dekorate/docker/apt/DockerAnnotationProcessor.java
- annotations/helm-annotations/src/main/java/io/dekorate/helm/apt/HelmAnnotationProcessor.java
- annotations/jaeger-annotations/src/main/java/io/dekorate/jaeger/apt/JaegerAgentAnnotationProcessor.java
- annotations/jib-annotations/src/main/java/io/dekorate/jib/apt/JibProcessor.java
- annotations/kind-annotations/src/main/java/io/dekorate/kind/apt/KindAnnotationProcessor.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/apt/KnativeAnnotationProcessor.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/KubernetesApplication.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/apt/KubernetesAnnotationProcessor.java
- annotations/minikube-annotations/src/main/java/io/dekorate/minikube/apt/MinikubeAnnotationProcessor.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/apt/OpenshiftAnnotationProcessor.java
- annotations/option-annotations/src/main/java/io/dekorate/option/apt/GeneratorOptionsProcessor.java
- annotations/option-annotations/src/main/java/io/dekorate/option/apt/JvmOptionsProcessor.java
- annotations/option-annotations/src/main/java/io/dekorate/option/apt/VcsOptionsProcessor.java
- annotations/prometheus-annotations/src/main/java/io/dekorate/prometheus/apt/ServiceMonitorAnnotationProcessor.java
- annotations/s2i-annotations/src/main/java/io/dekorate/s2i/apt/S2iAnnotationProcessor.java
- annotations/servicebinding-annotations/src/main/java/io/dekorate/servicebinding/apt/ServiceBindingAnnotationProcessor.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/apt/TektonAnnotationProcessor.java
- core/src/main/java/io/dekorate/apt/DekorateProcessor.java
- core/src/main/java/io/dekorate/processor/AbstractAnnotationProcessor.java
- frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/apt/ApplicationPathAnnotationProcessor.java
- frameworks/jaxrs/src/main/java/io/dekorate/jaxrs/apt/PathAnnotationProcessor.java
- frameworks/spring-boot/src/main/java/io/dekorate/spring/apt/SpringBootApplicationProcessor.java
- frameworks/spring-boot/src/main/java/io/dekorate/spring/apt/SpringBootBeanProcessor.java
- frameworks/spring-boot/src/main/java/io/dekorate/spring/apt/SpringBootWebProcessor.java
- frameworks/thorntail/src/main/java/io/dekorate/thorntail/ThorntailProcessor.java
As there is no good solution for this problem, given that we want to be compatible with a wide range of jdk version, we'll get hacky.
We'll follow the approach suggested by @dmlloyd in this pull request: https://github.com/kohsuke/metainf-services/pull/4.
> fix: annotation processsor now return SourceVersion.latest()

- .github/workflows/downstream-projects-check.yml
- .github/workflows/quarkus-main-ci.yml
This CI job is to verify if we introduce any breaking changes and also to verify we don't break the Quarkus functionality. 
Test output: https://github.com/Sgitario/dekorate/runs/6981118817?check_suite_focus=true which it fails because the `WithConfigReferences` interface changed.
> Add Quarkus Main CI job

- annotations/knative-annotations/src/main/java/io/dekorate/knative/manifest/KnativeManifestGenerator.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/manifest/KubernetesManifestGenerator.java
- core/src/main/java/io/dekorate/AbstractKubernetesManifestGenerator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyApplicationContainerDecorator.java
- tests/issue-1006-defaults-handling/pom.xml
- tests/issue-1006-defaults-handling/src/main/java/io/dekorate/annotationless/DemoApplication.java
- tests/issue-1006-defaults-handling/src/main/java/io/dekorate/annotationless/HelloController.java
- tests/issue-1006-defaults-handling/src/main/resources/application.properties
- tests/issue-1006-defaults-handling/src/main/resources/kubernetes/knative.yml
- tests/issue-1006-defaults-handling/src/main/resources/kubernetes/kubernetes.yml
- tests/issue-1006-defaults-handling/src/test/java/io/dekorate/example/Issue1006DefaultsTest.java
- tests/pom.xml
This is related to #1006 
The pull request introduces static config objects with default values for BaseConfg, KubernetesConfig, KnativeConfig in order to maintain an instance of the default configuration so that we only apply dekorators when non-default values are used.
For now, the issue covers `ImagePullPolicy` and also global/revision autoscaling of knative which seem to be the most common cases of probelms.
> fix: leverage builderWithDefaults to decouple handling of default values

- core/src/main/java/io/dekorate/Session.java
- core/src/main/java/io/dekorate/processor/AbstractAnnotationProcessor.java
Before these changes, if user provides a system property, for example: `dekorate.options.push=true`, and having another property in the `application.properties` file, for example `dekorate.options.input-path=k8s`, Dekorate ignored the properties from the application properties and only takes the one from the system properties.
> Merge properties from system properties and application properties

- core/src/main/java/io/dekorate/kubernetes/decorator/StatefulSetSelectorDecoratorFactory.java
- core/src/main/resources/META-INF/services/io.dekorate.SelectorDecoratorFactory
- tests/feat-886-kubernetes-deployment-kind-with-statefulset/src/test/java/io/dekorate/annotationless/Issue886Test.java
The labels were not being added when the deployment target is a StatefulSet resource. 
Added coverage in the Dekorate test suite and fix it.
This issue has been spotted by the CI https://github.com/dekorateio/dekorate/runs/7314857759?check_suite_focus=true. To be concrete, the following failures:
- KubernetesWithInputStatefulSetResourcesTest.assertGeneratedResources
- KubernetesWithStatefulSetResourceTest.assertGeneratedResources
- OpenshiftWithStatefulSetResourceTest.assertGeneratedResources
I've confirmed that with these changes, these tests are now passing.
> Fix labels in StatefulSet resources

- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyGlobalAutoscalingClassDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyGlobalContainerConcurrencyDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/decorator/ApplyGlobalRequestsPerSecondTargetDecorator.java
- annotations/knative-annotations/src/main/java/io/dekorate/knative/manifest/KnativeManifestGenerator.java
- tests/issue-939-knative-container-concurrency/src/test/java/io/dekorate/knative/Issue939KnativeContainerConcurrencyTest.java
This problem was spotted by https://github.com/dekorateio/dekorate/actions/runs/2663085841
Failing test: KnativeGlobalContainerConcurrencyTest
> fix: knative was generating an empty ConfigMap

- annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java
- core/src/main/java/io/dekorate/ResourceRegistry.java
This issue has been spotted in https://github.com/quarkiverse/quarkus-helm/issues/41 and after these changes, now it worked fine. 
It ensures deterministic order and will always use the last value found.
> Helm: Ensure deterministic order when applying config references

- .github/workflows/build.yml
- .github/workflows/manual_release.yml
- .github/workflows/release.yml
The pull request adds step for installing jbang in release workflows.
In addition it does add the step to the pr, just for verifying it works.
> fix: add missing step to install jbang

- core/src/main/java/io/dekorate/kubernetes/decorator/AbstractAddProbeDecorator.java
- examples/helm-on-kubernetes-example/src/main/resources/application.properties
- examples/helm-on-kubernetes-example/src/main/resources/kubernetes/kubernetes.yaml
- examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
- examples/helm-on-kubernetes-example/src/test/resources/expected-ingress.yaml
Fix https://github.com/dekorateio/dekorate/issues/1065
> Helm: Fix possible conflicts when using custom templates

- annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java
- docs/documentation/helm.md
- examples/helm-on-kubernetes-example/src/main/resources/application.properties
- examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
- tests/issue-fetch-helm-dependencies/pom.xml
- tests/issue-fetch-helm-dependencies/src/main/java/io/dekorate/example/DemoApplication.java
- tests/issue-fetch-helm-dependencies/src/main/java/io/dekorate/example/HelloController.java
- tests/issue-fetch-helm-dependencies/src/main/resources/application.properties
- tests/issue-fetch-helm-dependencies/src/test/java/io/dekorate/example/IssueHelmFetchDependencies.java
- tests/pom.xml
Related to https://github.com/quarkiverse/quarkus-helm/issues/93
> Fetch Helm dependencies before packaging

- annotations/kind-annotations/pom.xml
- annotations/kind-annotations/src/main/java/io/dekorate/kind/annotation/Kind.java
- annotations/kind-annotations/src/main/java/io/dekorate/kind/apt/KindAnnotationProcessor.java
- annotations/kind-annotations/src/main/java/io/dekorate/kind/config/DefaultKindConfigGenerator.java
- annotations/kind-annotations/src/main/java/io/dekorate/kind/config/KindConfigGenerator.java
- annotations/kind-annotations/src/main/java/io/dekorate/kind/decorator/ApplyPortToKindServiceDecorator.java
- annotations/kind-annotations/src/main/java/io/dekorate/kind/decorator/ApplyServiceTypeToKindServiceDecorator.java
- annotations/kind-annotations/src/main/java/io/dekorate/kind/manifest/KindManifestGenerator.java
- annotations/kind-annotations/src/main/java/io/dekorate/kind/manifest/KindManifestGeneratorFactory.java
- annotations/kind-annotations/src/main/resources/META-INF/services/io.dekorate.ManifestGeneratorFactory
- docs/_data/sidebar.yml
- docs/configuration-guide.md
- docs/documentation/kind.md
- examples/kind-example/Dockerfile
- examples/kind-example/pom.xml
- examples/kind-example/readme.md
- examples/kind-example/src/main/java/io/dekorate/example/App.java
- examples/kind-example/src/main/resources/application.properties
- examples/kind-example/src/test/java/io/dekorate/example/KindExampleTest.java
- examples/pom.xml
Plus, add the Kind page into the dekorate site. 
This pull request is related to https://github.com/quarkusio/quarkus/issues/28078
> Fix Kind extension to generate manifests

- docs/documentation/annotation-less-configuration.md
- examples/spring-boot-on-openshift-with-dekorate-profile-example/pom.xml
- examples/spring-boot-on-openshift-with-dekorate-profile-example/src/test/java/io/dekorate/example/SpringBootOnOpenshiftTest.java
- readme.md
The correct property is `dekorate.options.properties-profile`, not `dekorate.properties-profile`.  This changed recently when introducing the wrap config Options.  I've also fixed the example using this property to correctly cover this functionality.
> docs: fix documentation about the property `properties-profile`

- .github/workflows/integration-tests-with-dockerio.yml
- .github/workflows/integration-tests.yml
The Kubernetes tests are fixed by using manusa/actions-setup-minikube@v2.7.1
However, the OpenShift tests are still failing :/. Any help here @manusa ?
> Fix integration tests failures in Kubernetes and OpenShift

- annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java
Related to https://github.com/quarkiverse/quarkus-helm/issues/135
> Prioritize the user configuration over the decorate configuration

- annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java
- examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
- examples/helm-on-openshift-example/src/test/java/io/dekorate/example/HelmOpenshiftExampleTest.java
Related to https://github.com/quarkiverse/quarkus-helm/issues/154
> Do not camel case properties in the generated Helm manifests

- examples/frameworkless-on-kubernetes-example/pom.xml
- examples/frameworkless-on-openshift-example/pom.xml
- examples/minikube-example-with-properties/pom.xml
- examples/minikube-example/pom.xml
- examples/pom.xml
- examples/thorntail-on-kubernetes-example/pom.xml
- examples/thorntail-on-openshift-example/pom.xml
- examples/vertx-on-kubernetes-example/pom.xml
- examples/vertx-on-kubernetes-example/src/main/java/io/dekorate/example/Main.java
- examples/vertx-on-openshift-example/pom.xml
- examples/vertx-on-openshift-example/src/main/java/io/dekorate/example/Main.java
- pom.xml
- tests/feat-347-thorntail-annotationless/pom.xml
- tests/feat-openshift-probes/pom.xml
- tests/feat-openshift-probes/src/main/java/io/dekorate/example/Main.java
- tests/pom.xml
Necessary to fix CVE-2022-1471
Plus:
- Bump vertx version that is used in tests to not bring the Jackson dependencies as well
- Fix throntail examples to configure the war plugin and exclude the jackson dependecies (which are quite old)
> Bump Jackson from 2.12.3 to 2.14.1

- examples/frameworkless-on-kubernetes-example/pom.xml
- examples/frameworkless-on-openshift-example/pom.xml
- examples/minikube-example-with-properties/pom.xml
- examples/minikube-example/pom.xml
- examples/thorntail-on-kubernetes-example/pom.xml
- examples/thorntail-on-openshift-example/pom.xml
- examples/vertx-on-kubernetes-example/pom.xml
- examples/vertx-on-kubernetes-example/src/main/java/io/dekorate/example/Main.java
- examples/vertx-on-openshift-example/pom.xml
- examples/vertx-on-openshift-example/src/main/java/io/dekorate/example/Main.java
- pom.xml
- tests/feat-347-thorntail-annotationless/pom.xml
- tests/feat-openshift-probes/pom.xml
- tests/feat-openshift-probes/src/main/java/io/dekorate/example/Main.java
Necessary to fix CVE-2022-1471
Plus:
- Bump vertx version that is used in tests to not bring the Jackson dependencies as well
- Fix throntail examples to configure the war plugin and exclude the jackson dependecies (which are quite old)
> [2.11.x] Bump Jackson from 2.12.3 to 2.14.1

- annotations/certmanager-annotations/pom.xml
- annotations/certmanager-annotations/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
- annotations/servicebinding-annotations/pom.xml
Relates to https://github.com/quarkusio/quarkus/pull/30480
> Include only the fabric8 resources for model in the apt dependencies

- core/src/main/java/io/dekorate/utils/Serialization.java
Without this, I suddenly get errors like the following:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.fabric8.kubernetes.api.model.coordination.v1.Lease["spec"]->io.fabric8.kubernetes.api.model.coordination.v1.LeaseSpec["acquireTime"])
at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1909)
at com.fasterxml.jackson.databind.deser.impl.UnsupportedTypeDeserializer.deserialize(Unsuppo …
```
> Find and register  Modules in the ObjectMappers

- annotations/helm-annotations/src/main/java/io/dekorate/helm/listener/HelmWriterSessionListener.java
- examples/helm-on-kubernetes-example/src/main/resources/application.properties
Relates https://github.com/quarkiverse/quarkus-helm/pull/168
> Helm: Support configuration with the root alias already set

- core/src/main/java/io/dekorate/ResourceRegistry.java
- core/src/main/java/io/dekorate/utils/TopologicalSort.java
- core/src/test/java/io/dekorate/utils/TopologicalSortTest.java
Plus, add some test coverage with basic scenarios.
> Guarantee initial order for decorators to sort

- annotations/certmanager-annotations/src/main/java/io/dekorate/certmanager/adapter/CertificateConfigAdapter.java
- tests/issue-1158-spring-boot-certmanager-with-annotations/pom.xml
- tests/issue-1158-spring-boot-certmanager-with-annotations/src/main/java/io/dekorate/certmanager/DemoApplication.java
- tests/issue-1158-spring-boot-certmanager-with-annotations/src/main/java/io/dekorate/certmanager/HelloController.java
- tests/issue-1158-spring-boot-certmanager-with-annotations/src/main/resources/application.properties
- tests/issue-1158-spring-boot-certmanager-with-annotations/src/main/resources/k8s/common.yml
- tests/issue-1158-spring-boot-certmanager-with-annotations/src/test/java/io/dekorate/certmanager/SpringBootCertManagerTest.java
- tests/pom.xml
Fix https://github.com/dekorateio/dekorate/issues/1158
> Cert Manager: Fix extension to get config from annotations

- pom.xml
Changes: https://github.com/fabric8io/kubernetes-client/releases/tag/v6.5.0
> Bump Kubernetes Client to 6.5.0

- core/src/main/java/io/dekorate/AbstractKubernetesManifestGenerator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddMetadataToTemplateDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddSelectorToDeploymentSpecDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddToSelectorDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/DeploymentResourceFactory.java
- examples/pom.xml
- tests/pom.xml
This is meant to fix: https://github.com/quarkusio/quarkus/issues/31968
> fix: don't require selectors / metadata from existing resources

- core/src/main/java/io/dekorate/utils/Streams.java
The pull request cleans up temporary files that are used to support Streams.
Closing happens when stream closes which render the File no longer accessible.
> chore: delete tmp files that back streams when stream is closed

- core/src/main/java/io/dekorate/ConfigReference.java
- examples/helm-on-openshift-example/src/test/java/io/dekorate/example/HelmOpenshiftExampleTest.java
The property `s2i-java.builder-image` is invalid in the context of Helm. 
After these changes, this property will be changed to `s2iJava.builderImage`.
> Helm: Fix value property generated by OpenShift S2i

- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/decorator/ApplyReplicasToDeploymentConfigDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyImageDecorator.java
When Quarkus updates the image providing a different value, the default image is wrong.  
Unsetting the value will force the config reference to look up the image that has been used.
> Fix wrong image value when another decorator is overwritting it

- core/src/main/java/io/dekorate/kubernetes/decorator/AddAnnotationDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddEnvVarDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddLabelDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddMountDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddPortDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplicationContainerDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyArgsDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyCommandDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyImageDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyImagePullPolicyDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyLimitsCpuDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyLimitsMemoryDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyPortNameDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyRequestsCpuDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyRequestsMemoryDecorator.java
- core/src/main/java/io/dekorate/utils/Decorators.java
The pull request move containers dekorator order handling (before / after) methods to the `ApplicationContainerDecorator` class. Also, adds ApplicatonContainerDecorators to run after `AddInitContainerDecorator`.
> chore: centralize handling of container decorator order

- core/src/main/java/io/dekorate/kubernetes/decorator/AbstractAddProbeDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddPortDecorator.java
- docs/documentation/helm.md
- examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
- examples/helm-on-openshift-example/src/test/java/io/dekorate/example/HelmOpenshiftExampleTest.java
- tests/issue-knative-probes-helm/src/test/java/io/dekorate/knative/helm/KnativeWithHelmTest.java
The port number should be inline in several locations: deployment resources, service and HTTP probes.
> Helm: Bind port numbers in Helm values file

- core/src/main/java/io/dekorate/kubernetes/decorator/AddInitContainerDecorator.java
- core/src/main/java/io/dekorate/kubernetes/decorator/ApplyRequestsCpuDecorator.java
- tests/feat-overwrite-init-containers/pom.xml
- tests/feat-overwrite-init-containers/src/main/java/io/dekorate/annotationless/DemoApplication.java
- tests/feat-overwrite-init-containers/src/main/java/io/dekorate/annotationless/HelloController.java
- tests/feat-overwrite-init-containers/src/main/resources/application.properties
- tests/feat-overwrite-init-containers/src/test/java/io/dekorate/example/FeatOverwriteInitContainersTest.java
- tests/pom.xml
Related to https://github.com/quarkusio/quarkus/issues/33097#issuecomment-1533019528
> Support overwrite values from existing init-containers

- core/src/main/java/io/dekorate/utils/Ports.java
If the container ports are generated in a different order, the port is pickup in a different order. 
With this change, the logic to pick up the http to use is consistent.
I saw this issue when generating a Quarkus application. It randomly picks up the HTTP or the HTTPS in the generated Health probes.
> Ensure always pickup the same port

- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/manifest/TektonManifestGenerator.java
- core/src/main/java/io/dekorate/utils/Git.java
Once the first git remote is found, we iterate over all the values and overwrite the values.
For example, having:
```
[remote "origin"]
url = git@github.com:Sgitario/dekorate.git
fetch = +refs/heads/*:refs/remotes/origin/*
[remote "upstream"]
url = git@github.com:dekorateio/dekorate.git
fetch = +refs/heads/*:refs/remotes/upstream/*
[remote "auri"]
url = https://github.com/aureamunoz/dekorate
fetch = +refs/heads/*:refs/remotes/auri/*
```
Will produce a map of only an entry with:
```
'remote "origin"': https://github.com/aureamunoz/dekorate
```
Because https://github.com/aureamunoz/dekorate, it's the last value.
Also, the logic about remotes need to be aligned with this in the TektonManifestGenerator.
> fix: resolution of git remotes

- core/src/main/java/io/dekorate/kubernetes/decorator/AddServiceResourceDecorator.java
- docs/documentation/helm.md
- examples/helm-on-kubernetes-example/src/test/java/io/dekorate/example/HelmKubernetesExampleTest.java
Because changing this property would imply also changing other Service configuration that is not mapped, it does not make sense to add this mapping.
> Helm: Do not add the serviceType properties

- .github/workflows/integration-tests-with-dockerio.yml
- .github/workflows/integration-tests.yml
- annotations/knative-annotations/src/main/java/io/dekorate/knative/config/DefaultKnativeConfigGenerator.java
- annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/config/DefaultKubernetesConfigGenerator.java
- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/config/DefaultOpenshiftConfigGenerator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/annotation/TektonApplication.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddDeployStepDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddDockerSocketVolumeTaskDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddHostPathVolumeTaskDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddImageBuildStepDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddKanikoImageBuildStepDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddProjectBuildStepDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/manifest/TektonManifestGenerator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/step/BuildahBuildStep.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/step/DockerBuildStep.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/step/ImageBuildStep.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/step/KanikoBuildStep.java
- core/src/main/java/io/dekorate/kubernetes/configurator/ApplyImagePullSecretConfiguration.java
- core/src/main/java/io/dekorate/utils/Git.java
- core/src/main/java/io/dekorate/utils/Maps.java
- docs/documentation/service-binding.md
- docs/documentation/tekton.md
- examples/spring-boot-with-tekton-example/Dockerfile
- examples/spring-boot-with-tekton-example/readme.md
The integration with Tekton was broken for the following reasons:
- The service account integration was totally broken: so, neither private container registry could be used, nor the k8s manifests could be installed
- The kaniko image used to build and push the images was not working (one missing parameter and a wrong parameter related to the context)
- The extension was not supporting a multi-module project
- The image-pull-secret property was not taking into account: I had to revert https://github.com/dekorateio/dekorate/commit/1bcf751b08fca189fcb2f86d75a946da7dc09831
- Updated documentation and CI
All above have been fixed and addressed.
> fix: integration with Tekton

- pom.xml
Changes: https://github.com/fabric8io/kubernetes-client/releases/tag/v6.7.2
> bump Fabric8 Kubernetes Client to 6.7.2

- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/decorator/AddWorkspaceToPipelineTaskDecorator.java
- annotations/tekton-annotations/src/main/java/io/dekorate/tekton/manifest/TektonManifestGenerator.java
- examples/spring-boot-with-tekton-and-m2-pvc-example/src/main/resources/application.properties
- examples/spring-boot-with-tekton-and-m2-pvc-example/src/test/java/io/dekorate/example/SpringBootWithTektonTest.java
At the moment, the pipeline vs tasks resources generate the same persistent volumes but using different names.
With this fix, this is addressed to generate always the same volume persistent volume name.
> fix: tekton should create consistent names for persistent volumes

- .github/project.yml
While I am on PTO I am creating this pull request mostly to lay out my thoughts on how we should proceed regarding the next release....
Since we upgraded main to the kubernetes-client model to 6.8.0 that brings massive changes to the API, the next release from main *needs* to bump the major version to 4. 
Fixes for 3.x version should happen from 3.x branch.
We may hold this around for a while if we are planning for other breaking changes that should be included in 4.0.0.
> Release 4.0.0 ?

- annotations/openshift-annotations/src/main/java/io/dekorate/openshift/OpenshiftAnnotations.java
Fix openshift annotation for link to version control source
As per https://docs.openshift.com/container-platform/4.13/applications/odc-viewing-application-composition-using-topology-view.html#odc-labels-and-annotations-used-for-topology-view_viewing-application-composition-using-topology-view should be vcs-uri not vcs-url
> Fix openshift annotation for link to version control source

- annotations/servicebinding-annotations/src/main/java/io/dekorate/servicebinding/adapter/ServiceBindingConfigAdapter.java
- core/src/main/java/io/dekorate/kubernetes/annotation/Env.java
- core/src/main/java/io/dekorate/kubernetes/decorator/AddEnvVarDecorator.java
- core/src/test/java/io/dekorate/kubernetes/decorator/AddEnvVarDecoratorTest.java
> Add prefix to env
